#!/bin/bash


__debug()
{
    if [[ -n ${BASH_COMP_DEBUG_FILE} ]]; then
        echo "$*" >> "${BASH_COMP_DEBUG_FILE}"
    fi
}

__index_of_word()
{
    local w word=$1
    shift
    index=0
    for w in "$@"; do
        [[ $w = "$word" ]] && return
        index=$((index+1))
    done
    index=-1
}

__contains_word()
{
    local w word=$1; shift
    for w in "$@"; do
        [[ $w = "$word" ]] && return
    done
    return 1
}

__handle_reply()
{
    __debug "${FUNCNAME}"
    case $cur in
        -*)
            compopt -o nospace
            local allflags
            if [ ${#must_have_one_flag[@]} -ne 0 ]; then
                allflags=("${must_have_one_flag[@]}")
            else
                allflags=("${flags[*]} ${two_word_flags[*]}")
            fi
            COMPREPLY=( $(compgen -W "${allflags[*]}" -- "$cur") )
            [[ $COMPREPLY == *= ]] || compopt +o nospace
            return 0;
            ;;
    esac

    # check if we are handling a flag with special work handling
    local index
    __index_of_word "${prev}" "${flags_with_completion[@]}"
    if [[ ${index} -ge 0 ]]; then
        ${flags_completion[${index}]}
        return
    fi

    # we are parsing a flag and don't have a special handler, no completion
    if [[ ${cur} != "${words[cword]}" ]]; then
        return
    fi

    local completions
    if [[ ${#must_have_one_flag[@]} -ne 0 ]]; then
        completions=("${must_have_one_flag[@]}")
    elif [[ ${#must_have_one_noun[@]} -ne 0 ]]; then
        completions=("${must_have_one_noun[@]}")
    else
        completions=("${commands[@]}")
    fi
    COMPREPLY=( $(compgen -W "${completions[*]}" -- "$cur") )

    if [[ ${#COMPREPLY[@]} -eq 0 ]]; then
        declare -F __custom_func >/dev/null && __custom_func
    fi
}

# The arguments should be in the form "ext1|ext2|extn"
__handle_filename_extension_flag()
{
    local ext="$1"
    _filedir "@(${ext})"
}

__handle_flag()
{
    __debug "${FUNCNAME}: c is $c words[c] is ${words[c]}"

    # if a command required a flag, and we found it, unset must_have_one_flag()
    local flagname=${words[c]}
    # if the word contained an =
    if [[ ${words[c]} == *"="* ]]; then
        flagname=${flagname%=*} # strip everything after the =
        flagname="${flagname}=" # but put the = back
    fi
    __debug "${FUNCNAME}: looking for ${flagname}"
    if __contains_word "${flagname}" "${must_have_one_flag[@]}"; then
        must_have_one_flag=()
    fi

    # skip the argument to a two word flag
    if __contains_word "${words[c]}" "${two_word_flags[@]}"; then
        c=$((c+1))
        # if we are looking for a flags value, don't show commands
        if [[ $c -eq $cword ]]; then
            commands=()
        fi
    fi

    # skip the flag itself
    c=$((c+1))

}

__handle_noun()
{
    __debug "${FUNCNAME}: c is $c words[c] is ${words[c]}"

    if __contains_word "${words[c]}" "${must_have_one_noun[@]}"; then
        must_have_one_noun=()
    fi

    nouns+=("${words[c]}")
    c=$((c+1))
}

__handle_command()
{
    __debug "${FUNCNAME}: c is $c words[c] is ${words[c]}"

    local next_command
    if [[ -n ${last_command} ]]; then
        next_command="_${last_command}_${words[c]}"
    else
        next_command="_${words[c]}"
    fi
    c=$((c+1))
    __debug "${FUNCNAME}: looking for ${next_command}"
    declare -F $next_command >/dev/null && $next_command
}

__handle_word()
{
    if [[ $c -ge $cword ]]; then
        __handle_reply
	return
    fi
    __debug "${FUNCNAME}: c is $c words[c] is ${words[c]}"
    if [[ "${words[c]}" == -* ]]; then
	__handle_flag
    elif __contains_word "${words[c]}" "${commands[@]}"; then
        __handle_command
    else
        __handle_noun
    fi
    __handle_word
}

_oadm_new-project()
{
    last_command="oadm_new-project"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--admin=")
    flags+=("--admin-role=")
    flags+=("--description=")
    flags+=("--display-name=")
    flags+=("--help")
    flags+=("-h")
    flags+=("--node-selector=")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_policy_who-can()
{
    last_command="oadm_policy_who-can"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--all-namespaces")
    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_policy_add-role-to-user()
{
    last_command="oadm_policy_add-role-to-user"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")
    flags+=("--role-namespace=")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_policy_remove-role-from-user()
{
    last_command="oadm_policy_remove-role-from-user"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")
    flags+=("--role-namespace=")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_policy_remove-user()
{
    last_command="oadm_policy_remove-user"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_policy_add-role-to-group()
{
    last_command="oadm_policy_add-role-to-group"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")
    flags+=("--role-namespace=")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_policy_remove-role-from-group()
{
    last_command="oadm_policy_remove-role-from-group"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")
    flags+=("--role-namespace=")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_policy_remove-group()
{
    last_command="oadm_policy_remove-group"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_policy_add-cluster-role-to-user()
{
    last_command="oadm_policy_add-cluster-role-to-user"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_policy_remove-cluster-role-from-user()
{
    last_command="oadm_policy_remove-cluster-role-from-user"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_policy_add-cluster-role-to-group()
{
    last_command="oadm_policy_add-cluster-role-to-group"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_policy_remove-cluster-role-from-group()
{
    last_command="oadm_policy_remove-cluster-role-from-group"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_policy_reconcile-cluster-roles()
{
    last_command="oadm_policy_reconcile-cluster-roles"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--confirm")
    flags+=("--help")
    flags+=("-h")
    flags+=("--no-headers")
    flags+=("--output=")
    two_word_flags+=("-o")
    flags+=("--output-version=")
    flags+=("--template=")
    two_word_flags+=("-t")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_policy()
{
    last_command="oadm_policy"
    commands=()
    commands+=("who-can")
    commands+=("add-role-to-user")
    commands+=("remove-role-from-user")
    commands+=("remove-user")
    commands+=("add-role-to-group")
    commands+=("remove-role-from-group")
    commands+=("remove-group")
    commands+=("add-cluster-role-to-user")
    commands+=("remove-cluster-role-from-user")
    commands+=("add-cluster-role-to-group")
    commands+=("remove-cluster-role-from-group")
    commands+=("reconcile-cluster-roles")

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_router()
{
    last_command="oadm_router"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--create")
    flags+=("--credentials=")
    flags_with_completion+=("--credentials")
    flags_completion+=("__handle_filename_extension_flag kubeconfig")
    flags+=("--default-cert=")
    flags+=("--dry-run")
    flags+=("--help")
    flags+=("-h")
    flags+=("--host-network")
    flags+=("--images=")
    flags+=("--labels=")
    flags+=("--latest-images")
    flags+=("--no-headers")
    flags+=("--output=")
    two_word_flags+=("-o")
    flags+=("--output-version=")
    flags+=("--ports=")
    flags+=("--replicas=")
    flags+=("--selector=")
    flags+=("--service-account=")
    flags+=("--stats-password=")
    flags+=("--stats-port=")
    flags+=("--stats-user=")
    flags+=("--template=")
    two_word_flags+=("-t")
    flags+=("--type=")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_ipfailover()
{
    last_command="oadm_ipfailover"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--create")
    flags+=("--credentials=")
    flags_with_completion+=("--credentials")
    flags_completion+=("__handle_filename_extension_flag kubeconfig")
    flags+=("--help")
    flags+=("-h")
    flags+=("--images=")
    flags+=("--interface=")
    two_word_flags+=("-i")
    flags+=("--latest-images")
    flags+=("--no-headers")
    flags+=("--output=")
    two_word_flags+=("-o")
    flags+=("--output-version=")
    flags+=("--replicas=")
    two_word_flags+=("-r")
    flags+=("--selector=")
    two_word_flags+=("-l")
    flags+=("--service-account=")
    flags+=("--template=")
    two_word_flags+=("-t")
    flags+=("--type=")
    flags+=("--virtual-ips=")
    flags+=("--watch-port=")
    two_word_flags+=("-w")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_registry()
{
    last_command="oadm_registry"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--create")
    flags+=("--credentials=")
    flags_with_completion+=("--credentials")
    flags_completion+=("__handle_filename_extension_flag kubeconfig")
    flags+=("--dry-run")
    flags+=("--help")
    flags+=("-h")
    flags+=("--images=")
    flags+=("--labels=")
    flags+=("--latest-images")
    flags+=("--mount-host=")
    flags+=("--no-headers")
    flags+=("--output=")
    two_word_flags+=("-o")
    flags+=("--output-version=")
    flags+=("--ports=")
    flags+=("--replicas=")
    flags+=("--selector=")
    flags+=("--service-account=")
    flags+=("--template=")
    two_word_flags+=("-t")
    flags+=("--type=")
    flags+=("--volume=")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_build-chain()
{
    last_command="oadm_build-chain"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--all")
    flags+=("--help")
    flags+=("-h")
    flags+=("--output=")
    two_word_flags+=("-o")
    flags+=("--trigger-only")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_manage-node()
{
    last_command="oadm_manage-node"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--dry-run")
    flags+=("--evacuate")
    flags+=("--force")
    flags+=("--help")
    flags+=("-h")
    flags+=("--list-pods")
    flags+=("--no-headers")
    flags+=("--output=")
    two_word_flags+=("-o")
    flags+=("--output-version=")
    flags+=("--pod-selector=")
    flags+=("--schedulable")
    flags+=("--selector=")
    flags+=("--template=")
    two_word_flags+=("-t")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_prune_builds()
{
    last_command="oadm_prune_builds"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--confirm")
    flags+=("--help")
    flags+=("-h")
    flags+=("--keep-complete=")
    flags+=("--keep-failed=")
    flags+=("--keep-younger-than=")
    flags+=("--orphans")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_prune_deployments()
{
    last_command="oadm_prune_deployments"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--confirm")
    flags+=("--help")
    flags+=("-h")
    flags+=("--keep-complete=")
    flags+=("--keep-failed=")
    flags+=("--keep-younger-than=")
    flags+=("--orphans")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_prune_images()
{
    last_command="oadm_prune_images"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--certificate-authority=")
    flags+=("--confirm")
    flags+=("--help")
    flags+=("-h")
    flags+=("--keep-tag-revisions=")
    flags+=("--keep-younger-than=")
    flags+=("--registry-url=")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_prune()
{
    last_command="oadm_prune"
    commands=()
    commands+=("builds")
    commands+=("deployments")
    commands+=("images")

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_config_view()
{
    last_command="oadm_config_view"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--flatten")
    flags+=("--help")
    flags+=("-h")
    flags+=("--merge")
    flags+=("--minify")
    flags+=("--no-headers")
    flags+=("--output=")
    two_word_flags+=("-o")
    flags+=("--output-version=")
    flags+=("--raw")
    flags+=("--template=")
    two_word_flags+=("-t")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_config_set-cluster()
{
    last_command="oadm_config_set-cluster"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--api-version=")
    flags+=("--certificate-authority=")
    flags+=("--embed-certs")
    flags+=("--help")
    flags+=("-h")
    flags+=("--insecure-skip-tls-verify")
    flags+=("--server=")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_config_set-credentials()
{
    last_command="oadm_config_set-credentials"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--client-certificate=")
    flags+=("--client-key=")
    flags+=("--embed-certs")
    flags+=("--help")
    flags+=("-h")
    flags+=("--password=")
    flags+=("--token=")
    flags+=("--username=")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_config_set-context()
{
    last_command="oadm_config_set-context"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--cluster=")
    flags+=("--help")
    flags+=("-h")
    flags+=("--namespace=")
    flags+=("--user=")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_config_set()
{
    last_command="oadm_config_set"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_config_unset()
{
    last_command="oadm_config_unset"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_config_use-context()
{
    last_command="oadm_config_use-context"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_config()
{
    last_command="oadm_config"
    commands=()
    commands+=("view")
    commands+=("set-cluster")
    commands+=("set-credentials")
    commands+=("set-context")
    commands+=("set")
    commands+=("unset")
    commands+=("use-context")

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--config=")
    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_create-kubeconfig()
{
    last_command="oadm_create-kubeconfig"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--certificate-authority=")
    flags_with_completion+=("--certificate-authority")
    flags_completion+=("_filedir")
    flags+=("--client-certificate=")
    flags_with_completion+=("--client-certificate")
    flags_completion+=("_filedir")
    flags+=("--client-key=")
    flags_with_completion+=("--client-key")
    flags_completion+=("_filedir")
    flags+=("--help")
    flags+=("-h")
    flags+=("--kubeconfig=")
    flags_with_completion+=("--kubeconfig")
    flags_completion+=("_filedir")
    flags+=("--master=")
    flags+=("--namespace=")
    flags+=("--public-master=")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_create-api-client-config()
{
    last_command="oadm_create-api-client-config"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--basename=")
    flags+=("--certificate-authority=")
    flags_with_completion+=("--certificate-authority")
    flags_completion+=("_filedir")
    flags+=("--client-dir=")
    flags_with_completion+=("--client-dir")
    flags_completion+=("_filedir")
    flags+=("--groups=")
    flags+=("--help")
    flags+=("-h")
    flags+=("--master=")
    flags+=("--public-master=")
    flags+=("--signer-cert=")
    flags_with_completion+=("--signer-cert")
    flags_completion+=("_filedir")
    flags+=("--signer-key=")
    flags_with_completion+=("--signer-key")
    flags_completion+=("_filedir")
    flags+=("--signer-serial=")
    flags_with_completion+=("--signer-serial")
    flags_completion+=("_filedir")
    flags+=("--user=")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_create-bootstrap-project-template()
{
    last_command="oadm_create-bootstrap-project-template"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")
    flags+=("--name=")
    flags+=("--no-headers")
    flags+=("--output=")
    two_word_flags+=("-o")
    flags+=("--output-version=")
    flags+=("--template=")
    two_word_flags+=("-t")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_create-bootstrap-policy-file()
{
    last_command="oadm_create-bootstrap-policy-file"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--filename=")
    flags_with_completion+=("--filename")
    flags_completion+=("_filedir")
    flags+=("--help")
    flags+=("-h")
    flags+=("--openshift-namespace=")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_overwrite-policy()
{
    last_command="oadm_overwrite-policy"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--filename=")
    flags_with_completion+=("--filename")
    flags_completion+=("_filedir")
    flags+=("--force")
    flags+=("-f")
    flags+=("--help")
    flags+=("-h")
    flags+=("--master-config=")
    flags_with_completion+=("--master-config")
    flags_completion+=("__handle_filename_extension_flag yaml|yml")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_create-node-config()
{
    last_command="oadm_create-node-config"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--allow-disabled-docker")
    flags+=("--certificate-authority=")
    flags_with_completion+=("--certificate-authority")
    flags_completion+=("_filedir")
    flags+=("--client-certificate=")
    flags_with_completion+=("--client-certificate")
    flags_completion+=("_filedir")
    flags+=("--client-key=")
    flags_with_completion+=("--client-key")
    flags_completion+=("_filedir")
    flags+=("--dns-domain=")
    flags+=("--dns-ip=")
    flags+=("--help")
    flags+=("-h")
    flags+=("--hostnames=")
    flags+=("--images=")
    flags+=("--latest-images")
    flags+=("--listen=")
    flags+=("--master=")
    flags+=("--network-plugin=")
    flags+=("--node=")
    flags+=("--node-client-certificate-authority=")
    flags_with_completion+=("--node-client-certificate-authority")
    flags_completion+=("_filedir")
    flags+=("--node-dir=")
    flags_with_completion+=("--node-dir")
    flags_completion+=("_filedir")
    flags+=("--server-certificate=")
    flags_with_completion+=("--server-certificate")
    flags_completion+=("_filedir")
    flags+=("--server-key=")
    flags_with_completion+=("--server-key")
    flags_completion+=("_filedir")
    flags+=("--signer-cert=")
    flags_with_completion+=("--signer-cert")
    flags_completion+=("_filedir")
    flags+=("--signer-key=")
    flags_with_completion+=("--signer-key")
    flags_completion+=("_filedir")
    flags+=("--signer-serial=")
    flags_with_completion+=("--signer-serial")
    flags_completion+=("_filedir")
    flags+=("--volume-dir=")
    flags_with_completion+=("--volume-dir")
    flags_completion+=("_filedir")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_ca_create-master-certs()
{
    last_command="oadm_ca_create-master-certs"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--cert-dir=")
    flags_with_completion+=("--cert-dir")
    flags_completion+=("_filedir")
    flags+=("--help")
    flags+=("-h")
    flags+=("--hostnames=")
    flags+=("--master=")
    flags+=("--overwrite")
    flags+=("--public-master=")
    flags+=("--signer-name=")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_ca_create-key-pair()
{
    last_command="oadm_ca_create-key-pair"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")
    flags+=("--overwrite")
    flags+=("--private-key=")
    flags_with_completion+=("--private-key")
    flags_completion+=("_filedir")
    flags+=("--public-key=")
    flags_with_completion+=("--public-key")
    flags_completion+=("_filedir")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_ca_create-server-cert()
{
    last_command="oadm_ca_create-server-cert"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--cert=")
    flags_with_completion+=("--cert")
    flags_completion+=("_filedir")
    flags+=("--help")
    flags+=("-h")
    flags+=("--hostnames=")
    flags+=("--key=")
    flags_with_completion+=("--key")
    flags_completion+=("_filedir")
    flags+=("--overwrite")
    flags+=("--signer-cert=")
    flags_with_completion+=("--signer-cert")
    flags_completion+=("_filedir")
    flags+=("--signer-key=")
    flags_with_completion+=("--signer-key")
    flags_completion+=("_filedir")
    flags+=("--signer-serial=")
    flags_with_completion+=("--signer-serial")
    flags_completion+=("_filedir")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_ca_create-signer-cert()
{
    last_command="oadm_ca_create-signer-cert"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--cert=")
    flags_with_completion+=("--cert")
    flags_completion+=("_filedir")
    flags+=("--help")
    flags+=("-h")
    flags+=("--key=")
    flags_with_completion+=("--key")
    flags_completion+=("_filedir")
    flags+=("--name=")
    flags+=("--overwrite")
    flags+=("--serial=")
    flags_with_completion+=("--serial")
    flags_completion+=("_filedir")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_ca()
{
    last_command="oadm_ca"
    commands=()
    commands+=("create-master-certs")
    commands+=("create-key-pair")
    commands+=("create-server-cert")
    commands+=("create-signer-cert")

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm_options()
{
    last_command="oadm_options"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
}

_oadm()
{
    last_command="oadm"
    commands=()
    commands+=("new-project")
    commands+=("policy")
    commands+=("router")
    commands+=("ipfailover")
    commands+=("registry")
    commands+=("build-chain")
    commands+=("manage-node")
    commands+=("prune")
    commands+=("config")
    commands+=("create-kubeconfig")
    commands+=("create-api-client-config")
    commands+=("create-bootstrap-project-template")
    commands+=("create-bootstrap-policy-file")
    commands+=("overwrite-policy")
    commands+=("create-node-config")
    commands+=("ca")
    commands+=("options")

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--alsologtostderr")
    flags+=("--api-version=")
    flags+=("--boot-id-file=")
    flags+=("--certificate-authority=")
    flags+=("--client-certificate=")
    flags+=("--client-key=")
    flags+=("--cluster=")
    flags+=("--config=")
    flags+=("--container-hints=")
    flags+=("--context=")
    flags+=("--docker=")
    flags+=("--docker-only")
    flags+=("--docker-root=")
    flags+=("--docker-run=")
    flags+=("--enable-load-reader")
    flags+=("--event-storage-age-limit=")
    flags+=("--event-storage-event-limit=")
    flags+=("--global-housekeeping-interval=")
    flags+=("--google-json-key=")
    flags+=("--help")
    flags+=("-h")
    flags+=("--housekeeping-interval=")
    flags+=("--httptest.serve=")
    flags+=("--insecure-skip-tls-verify")
    flags+=("--log-backtrace-at=")
    flags+=("--log-cadvisor-usage")
    flags+=("--log-dir=")
    flags+=("--log-flush-frequency=")
    flags+=("--logtostderr")
    flags+=("--machine-id-file=")
    flags+=("--match-server-version")
    flags+=("--namespace=")
    two_word_flags+=("-n")
    flags+=("--server=")
    flags+=("--stderrthreshold=")
    flags+=("--token=")
    flags+=("--user=")
    flags+=("--v=")
    flags+=("--validate")
    flags+=("--vmodule=")

    must_have_one_flag=()
    must_have_one_noun=()
}

__start_oadm()
{
    local cur prev words cword
    _init_completion -s || return

    local c=0
    local flags=()
    local two_word_flags=()
    local flags_with_completion=()
    local flags_completion=()
    local commands=("oadm")
    local must_have_one_flag=()
    local must_have_one_noun=()
    local last_command
    local nouns=()

    __handle_word
}

complete -F __start_oadm oadm
# ex: ts=4 sw=4 et filetype=sh
