#!/bin/bash


__debug()
{
    if [[ -n ${BASH_COMP_DEBUG_FILE} ]]; then
        echo "$*" >> "${BASH_COMP_DEBUG_FILE}"
    fi
}

__index_of_word()
{
    local w word=$1
    shift
    index=0
    for w in "$@"; do
        [[ $w = "$word" ]] && return
        index=$((index+1))
    done
    index=-1
}

__contains_word()
{
    local w word=$1; shift
    for w in "$@"; do
        [[ $w = "$word" ]] && return
    done
    return 1
}

__handle_reply()
{
    __debug "${FUNCNAME}"
    case $cur in
        -*)
            compopt -o nospace
            local allflags
            if [ ${#must_have_one_flag[@]} -ne 0 ]; then
                allflags=("${must_have_one_flag[@]}")
            else
                allflags=("${flags[*]} ${two_word_flags[*]}")
            fi
            COMPREPLY=( $(compgen -W "${allflags[*]}" -- "$cur") )
            [[ $COMPREPLY == *= ]] || compopt +o nospace
            return 0;
            ;;
    esac

    # check if we are handling a flag with special work handling
    local index
    __index_of_word "${prev}" "${flags_with_completion[@]}"
    if [[ ${index} -ge 0 ]]; then
        ${flags_completion[${index}]}
        return
    fi

    # we are parsing a flag and don't have a special handler, no completion
    if [[ ${cur} != "${words[cword]}" ]]; then
        return
    fi

    local completions
    if [[ ${#must_have_one_flag[@]} -ne 0 ]]; then
        completions=("${must_have_one_flag[@]}")
    elif [[ ${#must_have_one_noun[@]} -ne 0 ]]; then
        completions=("${must_have_one_noun[@]}")
    else
        completions=("${commands[@]}")
    fi
    COMPREPLY=( $(compgen -W "${completions[*]}" -- "$cur") )

    if [[ ${#COMPREPLY[@]} -eq 0 ]]; then
        declare -F __custom_func >/dev/null && __custom_func
    fi
}

# The arguments should be in the form "ext1|ext2|extn"
__handle_filename_extension_flag()
{
    local ext="$1"
    _filedir "@(${ext})"
}

__handle_flag()
{
    __debug "${FUNCNAME}: c is $c words[c] is ${words[c]}"

    # if a command required a flag, and we found it, unset must_have_one_flag()
    local flagname=${words[c]}
    # if the word contained an =
    if [[ ${words[c]} == *"="* ]]; then
        flagname=${flagname%=*} # strip everything after the =
        flagname="${flagname}=" # but put the = back
    fi
    __debug "${FUNCNAME}: looking for ${flagname}"
    if __contains_word "${flagname}" "${must_have_one_flag[@]}"; then
        must_have_one_flag=()
    fi

    # skip the argument to a two word flag
    if __contains_word "${words[c]}" "${two_word_flags[@]}"; then
        c=$((c+1))
        # if we are looking for a flags value, don't show commands
        if [[ $c -eq $cword ]]; then
            commands=()
        fi
    fi

    # skip the flag itself
    c=$((c+1))

}

__handle_noun()
{
    __debug "${FUNCNAME}: c is $c words[c] is ${words[c]}"

    if __contains_word "${words[c]}" "${must_have_one_noun[@]}"; then
        must_have_one_noun=()
    fi

    nouns+=("${words[c]}")
    c=$((c+1))
}

__handle_command()
{
    __debug "${FUNCNAME}: c is $c words[c] is ${words[c]}"

    local next_command
    if [[ -n ${last_command} ]]; then
        next_command="_${last_command}_${words[c]}"
    else
        next_command="_${words[c]}"
    fi
    c=$((c+1))
    __debug "${FUNCNAME}: looking for ${next_command}"
    declare -F $next_command >/dev/null && $next_command
}

__handle_word()
{
    if [[ $c -ge $cword ]]; then
        __handle_reply
	return
    fi
    __debug "${FUNCNAME}: c is $c words[c] is ${words[c]}"
    if [[ "${words[c]}" == -* ]]; then
	__handle_flag
    elif __contains_word "${words[c]}" "${commands[@]}"; then
        __handle_command
    else
        __handle_noun
    fi
    __handle_word
}

# call osc get $1,
__osc_parse_get()
{
    local template
    template="{{ range .items  }}{{ .metadata.name }} {{ end }}"
    local osc_out
    if osc_out=$(osc get -o template --template="${template}" "$1" 2>/dev/null); then
        COMPREPLY=( $( compgen -W "${osc_out[*]}" -- "$cur" ) )
    fi
}

__osc_get_resource()
{
    if [[ ${#nouns[@]} -eq 0 ]]; then
        return 1
    fi
    __osc_parse_get ${nouns[${#nouns[@]} -1]}
}

# $1 is the name of the pod we want to get the list of containers inside
__osc_get_containers()
{
    local template
    template="{{ range .spec.containers  }}{{ .name }} {{ end }}"
    __debug ${FUNCNAME} "nouns are ${nouns[@]}"

    local len="${#nouns[@]}"
    if [[ ${len} -ne 1 ]]; then
        return
    fi
    local last=${nouns[${len} -1]}
    local osc_out
    if osc_out=$(osc get -o template --template="${template}" pods "${last}" 2>/dev/null); then
        COMPREPLY=( $( compgen -W "${osc_out[*]}" -- "$cur" ) )
    fi
}

# Require both a pod and a container to be specified
__osc_require_pod_and_container()
{
    if [[ ${#nouns[@]} -eq 0 ]]; then
        __osc_parse_get pods
        return 0
    fi;
    __osc_get_containers
    return 0
}

__custom_func() {
    case ${last_command} in
        osc_get | osc_describe | osc_delete)
	    __osc_get_resource
            return
            ;;
	osc_log)
	    __osc_require_pod_and_container
	    return
	    ;;
        *)
            ;;
    esac
}

_osc_login()
{
    last_command="osc_login"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")
    flags+=("--password=")
    two_word_flags+=("-p")
    flags+=("--username=")
    two_word_flags+=("-u")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc_logout()
{
    last_command="osc_logout"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc_project()
{
    last_command="osc_project"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc_new-project()
{
    last_command="osc_new-project"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--description=")
    flags+=("--display-name=")
    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc_new-app()
{
    last_command="osc_new-app"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--build=")
    flags+=("--code=")
    flags+=("--docker-image=")
    flags+=("--env=")
    two_word_flags+=("-e")
    flags+=("--group=")
    flags+=("--help")
    flags+=("-h")
    flags+=("--image=")
    two_word_flags+=("-i")
    flags+=("--labels=")
    two_word_flags+=("-l")
    flags+=("--name=")
    flags+=("--no-headers")
    flags+=("--output=")
    two_word_flags+=("-o")
    flags+=("--output-template=")
    flags+=("--output-version=")
    flags+=("--param=")
    two_word_flags+=("-p")
    flags+=("--template=")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc_status()
{
    last_command="osc_status"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc_start-build()
{
    last_command="osc_start-build"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--follow")
    flags+=("--from-build=")
    flags+=("--from-webhook=")
    flags+=("--git-post-receive=")
    flags+=("--help")
    flags+=("-h")
    flags+=("--list-webhooks=")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc_cancel-build()
{
    last_command="osc_cancel-build"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--dump-logs")
    flags+=("--help")
    flags+=("-h")
    flags+=("--restart")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc_build-logs()
{
    last_command="osc_build-logs"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--follow")
    flags+=("-f")
    flags+=("--help")
    flags+=("-h")
    flags+=("--nowait")
    flags+=("-w")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc_deploy()
{
    last_command="osc_deploy"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")
    flags+=("--latest")
    flags+=("--retry")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc_rollback()
{
    last_command="osc_rollback"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--change-scaling-settings")
    flags+=("--change-strategy")
    flags+=("--change-triggers")
    flags+=("--dry-run")
    flags+=("-d")
    flags+=("--help")
    flags+=("-h")
    flags+=("--output=")
    two_word_flags+=("-o")
    flags+=("--template=")
    two_word_flags+=("-t")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc_get()
{
    last_command="osc_get"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")
    flags+=("--no-headers")
    flags+=("--output=")
    two_word_flags+=("-o")
    flags+=("--output-version=")
    flags+=("--selector=")
    two_word_flags+=("-l")
    flags+=("--template=")
    two_word_flags+=("-t")
    flags+=("--watch")
    flags+=("-w")
    flags+=("--watch-only")

    must_have_one_flag=()
    must_have_one_noun=()
    must_have_one_noun+=("build")
    must_have_one_noun+=("buildconfig")
    must_have_one_noun+=("clusterpolicy")
    must_have_one_noun+=("clusterpolicybinding")
    must_have_one_noun+=("clusterrole")
    must_have_one_noun+=("clusterrolebinding")
    must_have_one_noun+=("componentstatus")
    must_have_one_noun+=("deployment")
    must_have_one_noun+=("deploymentconfig")
    must_have_one_noun+=("endpoints")
    must_have_one_noun+=("event")
    must_have_one_noun+=("identity")
    must_have_one_noun+=("image")
    must_have_one_noun+=("imagerepository")
    must_have_one_noun+=("imagerepositorytag")
    must_have_one_noun+=("imagestream")
    must_have_one_noun+=("imagestreamimage")
    must_have_one_noun+=("imagestreamtag")
    must_have_one_noun+=("ispersonalsubjectaccessreview")
    must_have_one_noun+=("limitrange")
    must_have_one_noun+=("namespace")
    must_have_one_noun+=("node")
    must_have_one_noun+=("oauthaccesstoken")
    must_have_one_noun+=("oauthauthorizetoken")
    must_have_one_noun+=("oauthclient")
    must_have_one_noun+=("oauthclientauthorization")
    must_have_one_noun+=("persistentvolume")
    must_have_one_noun+=("persistentvolumeclaim")
    must_have_one_noun+=("pod")
    must_have_one_noun+=("podtemplate")
    must_have_one_noun+=("policy")
    must_have_one_noun+=("policybinding")
    must_have_one_noun+=("project")
    must_have_one_noun+=("replicationcontroller")
    must_have_one_noun+=("resourcequota")
    must_have_one_noun+=("role")
    must_have_one_noun+=("rolebinding")
    must_have_one_noun+=("route")
    must_have_one_noun+=("secret")
    must_have_one_noun+=("service")
    must_have_one_noun+=("template")
    must_have_one_noun+=("user")
    must_have_one_noun+=("useridentitymapping")
}

_osc_describe()
{
    last_command="osc_describe"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
    must_have_one_noun+=("build")
    must_have_one_noun+=("buildconfig")
    must_have_one_noun+=("buildlog")
    must_have_one_noun+=("clusterpolicy")
    must_have_one_noun+=("clusterpolicybinding")
    must_have_one_noun+=("clusterrole")
    must_have_one_noun+=("clusterrolebinding")
    must_have_one_noun+=("deployment")
    must_have_one_noun+=("deploymentconfig")
    must_have_one_noun+=("identity")
    must_have_one_noun+=("image")
    must_have_one_noun+=("imagestream")
    must_have_one_noun+=("imagestreamimage")
    must_have_one_noun+=("imagestreamtag")
    must_have_one_noun+=("limitrange")
    must_have_one_noun+=("minion")
    must_have_one_noun+=("node")
    must_have_one_noun+=("persistentvolume")
    must_have_one_noun+=("persistentvolumeclaim")
    must_have_one_noun+=("pod")
    must_have_one_noun+=("policy")
    must_have_one_noun+=("policybinding")
    must_have_one_noun+=("project")
    must_have_one_noun+=("replicationcontroller")
    must_have_one_noun+=("resourcequota")
    must_have_one_noun+=("role")
    must_have_one_noun+=("rolebinding")
    must_have_one_noun+=("route")
    must_have_one_noun+=("service")
    must_have_one_noun+=("template")
    must_have_one_noun+=("user")
    must_have_one_noun+=("useridentitymapping")
}

_osc_create()
{
    last_command="osc_create"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--filename=")
    flags_with_completion+=("--filename")
    flags_completion+=("__handle_filename_extension_flag json|yaml|yml")
    two_word_flags+=("-f")
    flags_with_completion+=("-f")
    flags_completion+=("__handle_filename_extension_flag json|yaml|yml")
    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_flag+=("--filename=")
    must_have_one_flag+=("-f")
    must_have_one_noun=()
}

_osc_process()
{
    last_command="osc_process"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--filename=")
    two_word_flags+=("-f")
    flags+=("--help")
    flags+=("-h")
    flags+=("--labels=")
    two_word_flags+=("-l")
    flags+=("--no-headers")
    flags+=("--output=")
    two_word_flags+=("-o")
    flags+=("--output-version=")
    flags+=("--parameters")
    flags+=("--template=")
    two_word_flags+=("-t")
    flags+=("--value=")
    two_word_flags+=("-v")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc_edit()
{
    last_command="osc_edit"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--filename=")
    flags_with_completion+=("--filename")
    flags_completion+=("__handle_filename_extension_flag json|yaml|yml")
    two_word_flags+=("-f")
    flags_with_completion+=("-f")
    flags_completion+=("__handle_filename_extension_flag json|yaml|yml")
    flags+=("--help")
    flags+=("-h")
    flags+=("--output=")
    two_word_flags+=("-o")
    flags+=("--output-version=")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc_update()
{
    last_command="osc_update"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--filename=")
    flags_with_completion+=("--filename")
    flags_completion+=("__handle_filename_extension_flag json|yaml|yml")
    two_word_flags+=("-f")
    flags_with_completion+=("-f")
    flags_completion+=("__handle_filename_extension_flag json|yaml|yml")
    flags+=("--help")
    flags+=("-h")
    flags+=("--patch=")

    must_have_one_flag=()
    must_have_one_flag+=("--filename=")
    must_have_one_flag+=("-f")
    must_have_one_flag+=("--patch=")
    must_have_one_noun=()
}

_osc_delete()
{
    last_command="osc_delete"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--all")
    flags+=("--cascade")
    flags+=("--filename=")
    flags_with_completion+=("--filename")
    flags_completion+=("__handle_filename_extension_flag json|yaml|yml")
    two_word_flags+=("-f")
    flags_with_completion+=("-f")
    flags_completion+=("__handle_filename_extension_flag json|yaml|yml")
    flags+=("--grace-period=")
    flags+=("--help")
    flags+=("-h")
    flags+=("--selector=")
    two_word_flags+=("-l")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc_log()
{
    last_command="osc_log"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--follow")
    flags+=("-f")
    flags+=("--help")
    flags+=("-h")
    flags+=("--interactive")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc_exec()
{
    last_command="osc_exec"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--container=")
    two_word_flags+=("-c")
    flags+=("--help")
    flags+=("-h")
    flags+=("--pod=")
    two_word_flags+=("-p")
    flags+=("--stdin")
    flags+=("-i")
    flags+=("--tty")
    flags+=("-t")

    must_have_one_flag=()
    must_have_one_flag+=("--container=")
    must_have_one_flag+=("-c")
    must_have_one_flag+=("--pod=")
    must_have_one_flag+=("-p")
    must_have_one_noun=()
}

_osc_port-forward()
{
    last_command="osc_port-forward"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")
    flags+=("--pod=")
    two_word_flags+=("-p")

    must_have_one_flag=()
    must_have_one_flag+=("--pod=")
    must_have_one_flag+=("-p")
    must_have_one_noun=()
}

_osc_proxy()
{
    last_command="osc_proxy"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--api-prefix=")
    flags+=("--help")
    flags+=("-h")
    flags+=("--port=")
    two_word_flags+=("-p")
    flags+=("--www=")
    two_word_flags+=("-w")
    flags+=("--www-prefix=")
    two_word_flags+=("-P")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc_config_view()
{
    last_command="osc_config_view"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--flatten")
    flags+=("--help")
    flags+=("-h")
    flags+=("--merge")
    flags+=("--minify")
    flags+=("--no-headers")
    flags+=("--output=")
    two_word_flags+=("-o")
    flags+=("--output-version=")
    flags+=("--raw")
    flags+=("--template=")
    two_word_flags+=("-t")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc_config_set-cluster()
{
    last_command="osc_config_set-cluster"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--api-version=")
    flags+=("--certificate-authority=")
    flags+=("--embed-certs")
    flags+=("--help")
    flags+=("-h")
    flags+=("--insecure-skip-tls-verify")
    flags+=("--server=")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc_config_set-credentials()
{
    last_command="osc_config_set-credentials"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--auth-path=")
    flags+=("--client-certificate=")
    flags+=("--client-key=")
    flags+=("--embed-certs")
    flags+=("--help")
    flags+=("-h")
    flags+=("--password=")
    flags+=("--token=")
    flags+=("--username=")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc_config_set-context()
{
    last_command="osc_config_set-context"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--cluster=")
    flags+=("--help")
    flags+=("-h")
    flags+=("--namespace=")
    flags+=("--user=")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc_config_set()
{
    last_command="osc_config_set"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc_config_unset()
{
    last_command="osc_config_unset"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc_config_use-context()
{
    last_command="osc_config_use-context"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc_config()
{
    last_command="osc_config"
    commands=()
    commands+=("view")
    commands+=("set-cluster")
    commands+=("set-credentials")
    commands+=("set-context")
    commands+=("set")
    commands+=("unset")
    commands+=("use-context")

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--config=")
    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc_options()
{
    last_command="osc_options"
    commands=()

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--help")
    flags+=("-h")

    must_have_one_flag=()
    must_have_one_noun=()
}

_osc()
{
    last_command="osc"
    commands=()
    commands+=("login")
    commands+=("logout")
    commands+=("project")
    commands+=("new-project")
    commands+=("new-app")
    commands+=("status")
    commands+=("start-build")
    commands+=("cancel-build")
    commands+=("build-logs")
    commands+=("deploy")
    commands+=("rollback")
    commands+=("get")
    commands+=("describe")
    commands+=("create")
    commands+=("process")
    commands+=("edit")
    commands+=("update")
    commands+=("delete")
    commands+=("log")
    commands+=("exec")
    commands+=("port-forward")
    commands+=("proxy")
    commands+=("config")
    commands+=("options")

    flags=()
    two_word_flags=()
    flags_with_completion=()
    flags_completion=()

    flags+=("--allow_dynamic_housekeeping")
    flags+=("--alsologtostderr")
    flags+=("--api-version=")
    flags+=("--auth-path=")
    flags+=("--boot_id_file=")
    flags+=("--certificate-authority=")
    flags+=("--client-certificate=")
    flags+=("--client-key=")
    flags+=("--cluster=")
    flags+=("--config=")
    flags+=("--container_hints=")
    flags+=("--context=")
    flags+=("--docker=")
    flags+=("--docker_root=")
    flags+=("--docker_run=")
    flags+=("--enable_load_reader")
    flags+=("--global_housekeeping_interval=")
    flags+=("--google-json-key=")
    flags+=("--help")
    flags+=("-h")
    flags+=("--housekeeping_interval=")
    flags+=("--httptest.serve=")
    flags+=("--insecure-skip-tls-verify")
    flags+=("--log_backtrace_at=")
    flags+=("--log_cadvisor_usage")
    flags+=("--log_dir=")
    flags+=("--log_flush_frequency=")
    flags+=("--logtostderr")
    flags+=("--machine_id_file=")
    flags+=("--match-server-version")
    flags+=("--max_housekeeping_interval=")
    flags+=("--namespace=")
    two_word_flags+=("-n")
    flags+=("--server=")
    flags+=("--stderrthreshold=")
    flags+=("--token=")
    flags+=("--user=")
    flags+=("--v=")
    flags+=("--validate")
    flags+=("--vmodule=")

    must_have_one_flag=()
    must_have_one_noun=()
}

__start_osc()
{
    local cur prev words cword
    _init_completion -s || return

    local c=0
    local flags=()
    local two_word_flags=()
    local flags_with_completion=()
    local flags_completion=()
    local commands=("osc")
    local must_have_one_flag=()
    local must_have_one_noun=()
    local last_command
    local nouns=()

    __handle_word
}

complete -F __start_osc osc
# ex: ts=4 sw=4 et filetype=sh
