= v1.APIResourceList
{product-author}
{product-version}
:data-uri:
:icons:
:toc: macro
:toc-title:
:toclevels: 2

toc::[]

== Description
[%hardbreaks]
APIResourceList is a list of APIResource, it is used to expose the name of the resources supported in a specific group and version, and if the resource is namespaced.

== Object Schema
Expand or mouse-over a field for more information about it.

++++
<pre>
<div style="margin-left:13px;"><span title="(string) APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources">apiVersion</span>:
</div><div style="margin-left:13px;"><span title="(string) groupVersion is the group and version this APIResourceList is for.">groupVersion</span>:
</div><div style="margin-left:13px;"><span title="(string) Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds">kind</span>:
</div><details><summary><span title="(array) resources contains the name of the resources and if they are namespaced.">resources</span>:
</summary><details><summary>- <span title="(array) categories is a list of the grouped resources this resource belongs to (e.g. &#39;all&#39;)">categories</span>:
</summary><div style="margin-left:13px;">- - <span title="(string)">[string]</span>:
</div></details><div style="margin-left:13px;">  <span title="(string) group is the preferred group of the resource.  Empty implies the group of the containing resource list. For subresources, this may have a different value, for example: Scale&#34;.">group</span>:
</div><div style="margin-left:13px;">  <span title="(string) kind is the kind for the resource (e.g. &#39;Foo&#39; is the kind for a resource &#39;foo&#39;)">kind</span>:
</div><div style="margin-left:13px;">  <span title="(string) name is the plural name of the resource.">name</span>:
</div><div style="margin-left:13px;">  <span title="(boolean) namespaced indicates if a resource is namespaced or not.">namespaced</span>:
</div><details><summary>  <span title="(array) shortNames is a list of suggested short names of the resource.">shortNames</span>:
</summary><div style="margin-left:13px;">  - <span title="(string)">[string]</span>:
</div></details><div style="margin-left:13px;">  <span title="(string) singularName is the singular name of the resource.  This allows clients to handle plural and singular opaquely. The singularName is more correct for reporting status on a single item and both singular and plural are allowed from the kubectl CLI interface.">singularName</span>:
</div><details><summary>  <span title="(array) verbs is a list of supported kube verbs (this includes get, list, watch, create, update, patch, delete, deletecollection, and proxy)">verbs</span>:
</summary><div style="margin-left:13px;">  - <span title="(string)">[string]</span>:
</div></details><div style="margin-left:13px;">  <span title="(string) version is the preferred version of the resource.  Empty implies the version of the containing resource list For subresources, this may have a different value, for example: v1 (while inside a v1beta1 version of the core resource&#39;s group)&#34;.">version</span>:
</div></details>
</pre>
++++

== Operations

[[Get-api-v1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /api/v1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/api/v1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-admissionregistration.k8s.io-v1beta1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/admissionregistration.k8s.io/v1beta1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/admissionregistration.k8s.io/v1beta1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-apiregistration.k8s.io-v1beta1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/apiregistration.k8s.io/v1beta1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/apiregistration.k8s.io/v1beta1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-apps.openshift.io-v1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/apps.openshift.io/v1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/apps.openshift.io/v1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-apps-v1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/apps/v1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/apps/v1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-apps-v1beta1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/apps/v1beta1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/apps/v1beta1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-apps-v1beta2]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/apps/v1beta2/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/apps/v1beta2/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-authentication.k8s.io-v1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/authentication.k8s.io/v1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/authentication.k8s.io/v1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-authentication.k8s.io-v1beta1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/authentication.k8s.io/v1beta1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/authentication.k8s.io/v1beta1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-authorization.k8s.io-v1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/authorization.k8s.io/v1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/authorization.k8s.io/v1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-authorization.k8s.io-v1beta1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/authorization.k8s.io/v1beta1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/authorization.k8s.io/v1beta1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-authorization.openshift.io-v1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/authorization.openshift.io/v1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/authorization.openshift.io/v1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-autoscaling-v1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/autoscaling/v1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/autoscaling/v1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-autoscaling-v2beta1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/autoscaling/v2beta1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/autoscaling/v2beta1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-batch-v1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/batch/v1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/batch/v1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-batch-v1beta1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/batch/v1beta1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/batch/v1beta1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-batch-v2alpha1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/batch/v2alpha1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/batch/v2alpha1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-build.openshift.io-v1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/build.openshift.io/v1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/build.openshift.io/v1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-certificates.k8s.io-v1beta1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/certificates.k8s.io/v1beta1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/certificates.k8s.io/v1beta1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-events.k8s.io-v1beta1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/events.k8s.io/v1beta1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/events.k8s.io/v1beta1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-extensions-v1beta1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/extensions/v1beta1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/extensions/v1beta1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-image.openshift.io-v1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/image.openshift.io/v1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/image.openshift.io/v1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-network.openshift.io-v1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/network.openshift.io/v1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/network.openshift.io/v1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-networking.k8s.io-v1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/networking.k8s.io/v1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/networking.k8s.io/v1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-oauth.openshift.io-v1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/oauth.openshift.io/v1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/oauth.openshift.io/v1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-policy-v1beta1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/policy/v1beta1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/policy/v1beta1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-project.openshift.io-v1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/project.openshift.io/v1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/project.openshift.io/v1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-quota.openshift.io-v1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/quota.openshift.io/v1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/quota.openshift.io/v1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-rbac.authorization.k8s.io-v1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/rbac.authorization.k8s.io/v1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/rbac.authorization.k8s.io/v1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-rbac.authorization.k8s.io-v1beta1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/rbac.authorization.k8s.io/v1beta1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/rbac.authorization.k8s.io/v1beta1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-route.openshift.io-v1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/route.openshift.io/v1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/route.openshift.io/v1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-security.openshift.io-v1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/security.openshift.io/v1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/security.openshift.io/v1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-storage.k8s.io-v1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/storage.k8s.io/v1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/storage.k8s.io/v1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-storage.k8s.io-v1beta1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/storage.k8s.io/v1beta1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/storage.k8s.io/v1beta1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-template.openshift.io-v1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/template.openshift.io/v1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/template.openshift.io/v1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-apis-user.openshift.io-v1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /apis/user.openshift.io/v1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/user.openshift.io/v1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-oapi-v1]]
=== Get all APIResourceLists
Get available resources

==== HTTP request
----
GET /oapi/v1/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/oapi/v1/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIResourceList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf



