#
# OpenShift diagnostics image
# Used by network diagnostics (oadm diagnostics NetworkCheck)
#
# The standard name for this image is openshift/diagnostics-deployer

FROM openshift/origin-base

COPY scripts/openshift-network-debug /usr/bin/
