// This file was automatically generated by lister-gen

package internalversion

// ClusterResourceQuotaListerExpansion allows custom methods to be added to
// ClusterResourceQuotaLister.
type ClusterResourceQuotaListerExpansion interface{}
