apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  generateName: e2e-disruption-monitor-
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: e2e-disruption-monitor
subjects:
- kind: ServiceAccount
  name: disruption-monitor-sa
