kind: Namespace
apiVersion: v1
metadata:
  generateName: e2e-disruption-monitor-
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    apiserver.openshift.io/incluster-disruption: "true"
  annotations:
    workload.openshift.io/allowed: management
