apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: internal-lb
spec:
  maxUnavailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app: internal-lb-monitor
      apiserver.openshift.io/disruption-actor: poller
