apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: service-network
spec:
  maxUnavailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app: service-network-monitor
      apiserver.openshift.io/disruption-actor: poller
