apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  generateName: e2e-disruption-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: e2e-disruption-monitor
subjects:
- kind: ServiceAccount
  name: disruption-monitor-sa
