kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: e2e-disruption-monitor
rules:
  - verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
    apiGroups:
      - ''
    resources:
      - configmaps
