#!/bin/bash

[[ -f secret1 ]] && echo "relative-secret1=$(cat secret1)"
[[ -f secret2 ]] && echo "relative-secret2=$(cat secret2)"
[[ -f secret3 ]] && echo "relative-secret3=$(cat secret3)"

[[ -f /tmp/secret1 ]] && echo "secret1=$(cat /tmp/secret1)"
[[ -f /tmp/secret2 ]] && echo "secret2=$(cat /tmp/secret2)"
[[ -f /tmp/secret3 ]] && echo "secret3=$(cat /tmp/secret3)"
