apiVersion: v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: alternate-cluster-admin
  resourceVersion: "RESOURCE_VERSION"
rules:
  - apiGroups:
      - '*'
    attributeRestrictions: null
    resources:
      - '*'
    verbs:
      - create
      - update
      - patch
      - delete
      - get
      - list
      - watch
  - attributeRestrictions: null
    nonResourceURLs:
      - '*'
    resources: []
    verbs:
      - '*'