#!/bin/bash

set -o nounset

config_file=/var/lib/nginx/conf/nginx.config
if [ -f /var/lib/nginx/logs/nginx.pid ]; then
  /usr/sbin/nginx -c ${config_file} -s reload
  reload_status=$?
else
  /usr/sbin/nginx -c ${config_file}
  reload_status=$?
fi
exit $reload_status
