= v1.BuildConfig
{product-author}
{product-version}
:data-uri:
:icons:
:toc: macro
:toc-title:
:toclevels: 2

toc::[]

== Description
[%hardbreaks]
Build configurations define a build process for new Docker images. There are three types of builds possible - a Docker build using a Dockerfile, a Source-to-Image build that uses a specially prepared base image that accepts source code that it can make runnable, and a custom build that can run // arbitrary Docker images as a base and accept the build parameters. Builds run on the cluster and on completion are pushed to the Docker registry specified in the "output" section. A build can be triggered via a webhook, when the base image changes, or when a user manually requests a new build be // created.

Each build created by a build configuration is numbered and refers back to its parent configuration. Multiple builds can be triggered at once. Builds that do not have "output" set can be used to test code or run a verification build.

== Object Schema
Expand or mouse-over a field for more information about it.

++++
<pre>
<div style="margin-left:13px;"><span title="(string) APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources">apiVersion</span>:
</div><div style="margin-left:13px;"><span title="(string) Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds">kind</span>:
</div><details open><summary><span title="(v1.ObjectMeta) metadata for BuildConfig.">metadata</span>:
</summary><details><summary>  <span title="(object) Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations">annotations</span>:
</summary><div style="margin-left:13px;">    <span title="(string)">[string]</span>:
</div></details><div style="margin-left:13px;">  <span title="(string) The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request.">clusterName</span>:
</div><div style="margin-left:13px;">  <span title="(v1.Time) CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata">creationTimestamp</span>:
</div><div style="margin-left:13px;">  <span title="(integer) Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only.">deletionGracePeriodSeconds</span>:
</div><div style="margin-left:13px;">  <span title="(v1.Time) DeletionTimestamp is RFC 3339 date and time at which this resource will be deleted. This field is set by the server when a graceful deletion is requested by the user, and is not directly settable by a client. The resource is expected to be deleted (no longer visible from resource lists, and not reachable by name) after the time in this field, once the finalizers list is empty. As long as the finalizers list contains items, deletion is blocked. Once the deletionTimestamp is set, this value may not be unset or be set further into the future, although it may be shortened or the resource may be deleted prior to this time. For example, a user may request that a pod is deleted in 30 seconds. The Kubelet will react by sending a graceful termination signal to the containers in the pod. After that 30 seconds, the Kubelet will send a hard termination signal (SIGKILL) to the container and after cleanup, remove the pod from the API. In the presence of network partitions, this object may still exist after this timestamp, until an administrator or automated process can determine the resource is fully terminated. If not set, graceful deletion of the object has not been requested.

Populated by the system when a graceful deletion is requested. Read-only. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata">deletionTimestamp</span>:
</div><details><summary>  <span title="(array) Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed.">finalizers</span>:
</summary><div style="margin-left:13px;">  - <span title="(string)">[string]</span>:
</div></details><div style="margin-left:13px;">  <span title="(string) GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.

If this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).

Applied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#idempotency">generateName</span>:
</div><div style="margin-left:13px;">  <span title="(integer) A sequence number representing a specific generation of the desired state. Populated by the system. Read-only.">generation</span>:
</div><details><summary>  <span title="(v1.Initializers) An initializer is a controller which enforces some system invariant at object creation time. This field is a list of initializers that have not yet acted on this object. If nil or empty, this object has been completely initialized. Otherwise, the object is considered uninitialized and is hidden (in list/watch and get calls) from clients that haven&#39;t explicitly asked to observe uninitialized objects.

When an object is created, the system will populate this list with the current set of initializers. Only privileged users may set or modify this list. Once it is empty, it may not be modified further by any user.">initializers</span>:
</summary><details><summary>    <span title="(array) Pending is a list of initializers that must execute in order before this object is visible. When the last pending initializer is removed, and no failing result is set, the initializers struct will be set to nil and the object is considered as initialized and visible to all clients.">pending</span>:
</summary><div style="margin-left:13px;">    - <span title="(string) name of the process that is responsible for initializing this object.">name</span>:
</div></details><details><summary>    <span title="(v1.Status) If result is set with the Failure field, the object will be persisted to storage and then deleted, ensuring that other clients can observe the deletion.">result</span>:
</summary><div style="margin-left:13px;">      <span title="(string) APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources">apiVersion</span>:
</div><div style="margin-left:13px;">      <span title="(integer) Suggested HTTP return code for this status, 0 if not set.">code</span>:
</div><details><summary>      <span title="(v1.StatusDetails) Extended data associated with the reason.  Each reason may define its own extended details. This field is optional and the data returned is not guaranteed to conform to any schema except that defined by the reason type.">details</span>:
</summary><details><summary>        <span title="(array) The Causes array includes more details associated with the StatusReason failure. Not all StatusReasons may provide detailed causes.">causes</span>:
</summary><div style="margin-left:13px;">        - <span title="(string) The field of the resource that has caused this error, as named by its JSON serialization. May include dot and postfix notation for nested attributes. Arrays are zero-indexed.  Fields may appear more than once in an array of causes due to fields having multiple errors. Optional.

Examples:
  &#34;name&#34; - the field &#34;name&#34; on the current resource
  &#34;items[0].name&#34; - the field &#34;name&#34; on the first array entry in &#34;items&#34;">field</span>:
</div><div style="margin-left:13px;">          <span title="(string) A human-readable description of the cause of the error.  This field may be presented as-is to a reader.">message</span>:
</div><div style="margin-left:13px;">          <span title="(string) A machine-readable description of the cause of the error. If this value is empty there is no information available.">reason</span>:
</div></details><div style="margin-left:13px;">        <span title="(string) The group attribute of the resource associated with the status StatusReason.">group</span>:
</div><div style="margin-left:13px;">        <span title="(string) The kind attribute of the resource associated with the status StatusReason. On some operations may differ from the requested resource Kind. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds">kind</span>:
</div><div style="margin-left:13px;">        <span title="(string) The name attribute of the resource associated with the status StatusReason (when there is a single name which can be described).">name</span>:
</div><div style="margin-left:13px;">        <span title="(integer) If specified, the time in seconds before the operation should be retried. Some errors may indicate the client must take an alternate action - for those errors this field may indicate how long to wait before taking the alternate action.">retryAfterSeconds</span>:
</div><div style="margin-left:13px;">        <span title="(string) UID of the resource. (when there is a single resource which can be described). More info: http://kubernetes.io/docs/user-guide/identifiers#uids">uid</span>:
</div></details><div style="margin-left:13px;">      <span title="(string) Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds">kind</span>:
</div><div style="margin-left:13px;">      <span title="(string) A human-readable description of the status of this operation.">message</span>:
</div><details><summary>      <span title="(v1.ListMeta) Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds">metadata</span>:
</summary><div style="margin-left:13px;">        <span title="(string) continue may be set if the user set a limit on the number of items returned, and indicates that the server has more data available. The value is opaque and may be used to issue another request to the endpoint that served this list to retrieve the next set of available objects. Continuing a list may not be possible if the server configuration has changed or more than a few minutes have passed. The resourceVersion field returned when using this continue value will be identical to the value in the first response.">continue</span>:
</div><div style="margin-left:13px;">        <span title="(string) String that identifies the server&#39;s internal version of this object that can be used by clients to determine when objects have changed. Value must be treated as opaque by clients and passed unmodified back to the server. Populated by the system. Read-only. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#concurrency-control-and-consistency">resourceVersion</span>:
</div><div style="margin-left:13px;">        <span title="(string) selfLink is a URL representing this object. Populated by the system. Read-only.">selfLink</span>:
</div></details><div style="margin-left:13px;">      <span title="(string) A machine-readable description of why this operation is in the &#34;Failure&#34; status. If this value is empty there is no information available. A Reason clarifies an HTTP status code but does not override it.">reason</span>:
</div><div style="margin-left:13px;">      <span title="(string) Status of the operation. One of: &#34;Success&#34; or &#34;Failure&#34;. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status">status</span>:
</div></details></details><details><summary>  <span title="(object) Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels">labels</span>:
</summary><div style="margin-left:13px;">    <span title="(string)">[string]</span>:
</div></details><div style="margin-left:13px;">  <span title="(string) Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names">name</span>:
</div><div style="margin-left:13px;">  <span title="(string) Namespace defines the space within each name must be unique. An empty namespace is equivalent to the &#34;default&#34; namespace, but &#34;default&#34; is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.

Must be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces">namespace</span>:
</div><details><summary>  <span title="(array) List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller.">ownerReferences</span>:
</summary><div style="margin-left:13px;">  - <span title="(string) API version of the referent.">apiVersion</span>:
</div><div style="margin-left:13px;">    <span title="(boolean) If true, AND if the owner has the &#34;foregroundDeletion&#34; finalizer, then the owner cannot be deleted from the key-value store until this reference is removed. Defaults to false. To set this field, a user needs &#34;delete&#34; permission of the owner, otherwise 422 (Unprocessable Entity) will be returned.">blockOwnerDeletion</span>:
</div><div style="margin-left:13px;">    <span title="(boolean) If true, this reference points to the managing controller.">controller</span>:
</div><div style="margin-left:13px;">    <span title="(string) Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds">kind</span>:
</div><div style="margin-left:13px;">    <span title="(string) Name of the referent. More info: http://kubernetes.io/docs/user-guide/identifiers#names">name</span>:
</div><div style="margin-left:13px;">    <span title="(string) UID of the referent. More info: http://kubernetes.io/docs/user-guide/identifiers#uids">uid</span>:
</div></details><div style="margin-left:13px;">  <span title="(string) An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.

Populated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#concurrency-control-and-consistency">resourceVersion</span>:
</div><div style="margin-left:13px;">  <span title="(string) SelfLink is a URL representing this object. Populated by the system. Read-only.">selfLink</span>:
</div><div style="margin-left:13px;">  <span title="(string) UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.

Populated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids">uid</span>:
</div></details><details open><summary><span title="(v1.BuildConfigSpec) spec holds all the input necessary to produce a new build, and the conditions when to trigger them.">spec</span>:
</summary><div style="margin-left:13px;">  <span title="(integer) completionDeadlineSeconds is an optional duration in seconds, counted from the time when a build pod gets scheduled in the system, that the build may be active on a node before the system actively tries to terminate the build; value must be positive integer">completionDeadlineSeconds</span>:
</div><div style="margin-left:13px;">  <span title="(integer) failedBuildsHistoryLimit is the number of old failed builds to retain. If not specified, all failed builds are retained.">failedBuildsHistoryLimit</span>:
</div><details><summary>  <span title="(object) nodeSelector is a selector which must be true for the build pod to fit on a node If nil, it can be overridden by default build nodeselector values for the cluster. If set to an empty map or a map with any values, default build nodeselector values are ignored.">nodeSelector</span>:
</summary><div style="margin-left:13px;">    <span title="(string)">[string]</span>:
</div></details><details><summary>  <span title="(v1.BuildOutput) output describes the Docker image the Strategy should produce.">output</span>:
</summary><details><summary>    <span title="(array) imageLabels define a list of labels that are applied to the resulting image. If there are multiple labels with the same name then the last one in the list is used.">imageLabels</span>:
</summary><div style="margin-left:13px;">    - <span title="(string) name defines the name of the label. It must have non-zero length.">name</span>:
</div><div style="margin-left:13px;">      <span title="(string) value defines the literal value of the label.">value</span>:
</div></details><details><summary>    <span title="(v1.LocalObjectReference) PushSecret is the name of a Secret that would be used for setting up the authentication for executing the Docker push to authentication enabled Docker Registry (or Docker Hub).">pushSecret</span>:
</summary><div style="margin-left:13px;">      <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div></details><details><summary>    <span title="(v1.ObjectReference) to defines an optional location to push the output of this build to. Kind must be one of &#39;ImageStreamTag&#39; or &#39;DockerImage&#39;. This value will be used to look up a Docker image repository to push to. In the case of an ImageStreamTag, the ImageStreamTag will be looked for in the namespace of the build unless Namespace is specified.">to</span>:
</summary><div style="margin-left:13px;">      <span title="(string) API version of the referent.">apiVersion</span>:
</div><div style="margin-left:13px;">      <span title="(string) If referring to a piece of an object instead of an entire object, this string should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2]. For example, if the object reference is to a container within a pod, this would take on a value like: &#34;spec.containers{name}&#34; (where &#34;name&#34; refers to the name of the container that triggered the event) or if no container name is specified &#34;spec.containers[2]&#34; (container with index 2 in this pod). This syntax is chosen only to have some well-defined way of referencing a part of an object.">fieldPath</span>:
</div><div style="margin-left:13px;">      <span title="(string) Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds">kind</span>:
</div><div style="margin-left:13px;">      <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div><div style="margin-left:13px;">      <span title="(string) Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/">namespace</span>:
</div><div style="margin-left:13px;">      <span title="(string) Specific resourceVersion to which this reference is made, if any. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#concurrency-control-and-consistency">resourceVersion</span>:
</div><div style="margin-left:13px;">      <span title="(string) UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids">uid</span>:
</div></details></details><details><summary>  <span title="(v1.BuildPostCommitSpec) postCommit is a build hook executed after the build output image is committed, before it is pushed to a registry.">postCommit</span>:
</summary><details><summary>    <span title="(array) args is a list of arguments that are provided to either Command, Script or the Docker image&#39;s default entrypoint. The arguments are placed immediately after the command to be run.">args</span>:
</summary><div style="margin-left:13px;">    - <span title="(string)">[string]</span>:
</div></details><details><summary>    <span title="(array) command is the command to run. It may not be specified with Script. This might be needed if the image doesn&#39;t have `/bin/sh`, or if you do not want to use a shell. In all other cases, using Script might be more convenient.">command</span>:
</summary><div style="margin-left:13px;">    - <span title="(string)">[string]</span>:
</div></details><div style="margin-left:13px;">    <span title="(string) script is a shell script to be run with `/bin/sh -ic`. It may not be specified with Command. Use Script when a shell script is appropriate to execute the post build hook, for example for running unit tests with `rake test`. If you need control over the image entrypoint, or if the image does not have `/bin/sh`, use Command and/or Args. The `-i` flag is needed to support CentOS and RHEL images that use Software Collections (SCL), in order to have the appropriate collections enabled in the shell. E.g., in the Ruby image, this is necessary to make `ruby`, `bundle` and other binaries available in the PATH.">script</span>:
</div></details><details><summary>  <span title="(v1.ResourceRequirements) resources computes resource requirements to execute the build.">resources</span>:
</summary><details><summary>    <span title="(object) Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/">limits</span>:
</summary><div style="margin-left:13px;">      <span title="(string)">[string]</span>:
</div></details><details><summary>    <span title="(object) Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/">requests</span>:
</summary><div style="margin-left:13px;">      <span title="(string)">[string]</span>:
</div></details></details><details><summary>  <span title="(v1.SourceRevision) revision is the information from the source for a specific repo snapshot. This is optional.">revision</span>:
</summary><details><summary>    <span title="(v1.GitSourceRevision) Git contains information about git-based build source">git</span>:
</summary><details><summary>      <span title="(v1.SourceControlUser) author is the author of a specific commit">author</span>:
</summary><div style="margin-left:13px;">        <span title="(string) email of the source control user">email</span>:
</div><div style="margin-left:13px;">        <span title="(string) name of the source control user">name</span>:
</div></details><div style="margin-left:13px;">      <span title="(string) commit is the commit hash identifying a specific commit">commit</span>:
</div><details><summary>      <span title="(v1.SourceControlUser) committer is the committer of a specific commit">committer</span>:
</summary><div style="margin-left:13px;">        <span title="(string) email of the source control user">email</span>:
</div><div style="margin-left:13px;">        <span title="(string) name of the source control user">name</span>:
</div></details><div style="margin-left:13px;">      <span title="(string) message is the description of a specific commit">message</span>:
</div></details><div style="margin-left:13px;">    <span title="(string) type of the build source, may be one of &#39;Source&#39;, &#39;Dockerfile&#39;, &#39;Binary&#39;, or &#39;Images&#39;">type</span>:
</div></details><div style="margin-left:13px;">  <span title="(string) RunPolicy describes how the new build created from this build configuration will be scheduled for execution. This is optional, if not specified we default to &#34;Serial&#34;.">runPolicy</span>:
</div><div style="margin-left:13px;">  <span title="(string) serviceAccount is the name of the ServiceAccount to use to run the pod created by this build. The pod will be allowed to use secrets referenced by the ServiceAccount">serviceAccount</span>:
</div><details><summary>  <span title="(v1.BuildSource) source describes the SCM in use.">source</span>:
</summary><details><summary>    <span title="(v1.BinaryBuildSource) binary builds accept a binary as their input. The binary is generally assumed to be a tar, gzipped tar, or zip file depending on the strategy. For Docker builds, this is the build context and an optional Dockerfile may be specified to override any Dockerfile in the build context. For Source builds, this is assumed to be an archive as described above. For Source and Docker builds, if binary.asFile is set the build will receive a directory with a single file. contextDir may be used when an archive is provided. Custom builds will receive this binary as input on STDIN.">binary</span>:
</summary><div style="margin-left:13px;">      <span title="(string) asFile indicates that the provided binary input should be considered a single file within the build input. For example, specifying &#34;webapp.war&#34; would place the provided binary as `/webapp.war` for the builder. If left empty, the Docker and Source build strategies assume this file is a zip, tar, or tar.gz file and extract it as the source. The custom strategy receives this binary as standard input. This filename may not contain slashes or be &#39;..&#39; or &#39;.&#39;.">asFile</span>:
</div></details><div style="margin-left:13px;">    <span title="(string) contextDir specifies the sub-directory where the source code for the application exists. This allows to have buildable sources in directory other than root of repository.">contextDir</span>:
</div><div style="margin-left:13px;">    <span title="(string) dockerfile is the raw contents of a Dockerfile which should be built. When this option is specified, the FROM may be modified based on your strategy base image and additional ENV stanzas from your strategy environment will be added after the FROM, but before the rest of your Dockerfile stanzas. The Dockerfile source type may be used with other options like git - in those cases the Git repo will have any innate Dockerfile replaced in the context dir.">dockerfile</span>:
</div><details><summary>    <span title="(v1.GitBuildSource) git contains optional information about git build source">git</span>:
</summary><div style="margin-left:13px;">      <span title="(string) httpProxy is a proxy used to reach the git repository over http">httpProxy</span>:
</div><div style="margin-left:13px;">      <span title="(string) httpsProxy is a proxy used to reach the git repository over https">httpsProxy</span>:
</div><div style="margin-left:13px;">      <span title="(string) noProxy is the list of domains for which the proxy should not be used">noProxy</span>:
</div><div style="margin-left:13px;">      <span title="(string) ref is the branch/tag/ref to build.">ref</span>:
</div><div style="margin-left:13px;">      <span title="(string) uri points to the source that will be built. The structure of the source will depend on the type of build to run">uri</span>:
</div></details><details><summary>    <span title="(array) images describes a set of images to be used to provide source for the build">images</span>:
</summary><details><summary>    - <span title="(array) A list of image names that this source will be used in place of during a multi-stage Docker image build. For instance, a Dockerfile that uses &#34;COPY --from=nginx:latest&#34; will first check for an image source that has &#34;nginx:latest&#34; in this field before attempting to pull directly. If the Dockerfile does not reference an image source it is ignored. This field and paths may both be set, in which case the contents will be used twice.">as</span>:
</summary><div style="margin-left:13px;">    - - <span title="(string)">[string]</span>:
</div></details><details><summary>      <span title="(v1.ObjectReference) from is a reference to an ImageStreamTag, ImageStreamImage, or DockerImage to copy source from.">from</span>:
</summary><div style="margin-left:13px;">        <span title="(string) API version of the referent.">apiVersion</span>:
</div><div style="margin-left:13px;">        <span title="(string) If referring to a piece of an object instead of an entire object, this string should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2]. For example, if the object reference is to a container within a pod, this would take on a value like: &#34;spec.containers{name}&#34; (where &#34;name&#34; refers to the name of the container that triggered the event) or if no container name is specified &#34;spec.containers[2]&#34; (container with index 2 in this pod). This syntax is chosen only to have some well-defined way of referencing a part of an object.">fieldPath</span>:
</div><div style="margin-left:13px;">        <span title="(string) Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds">kind</span>:
</div><div style="margin-left:13px;">        <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div><div style="margin-left:13px;">        <span title="(string) Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/">namespace</span>:
</div><div style="margin-left:13px;">        <span title="(string) Specific resourceVersion to which this reference is made, if any. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#concurrency-control-and-consistency">resourceVersion</span>:
</div><div style="margin-left:13px;">        <span title="(string) UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids">uid</span>:
</div></details><details><summary>      <span title="(array) paths is a list of source and destination paths to copy from the image. This content will be copied into the build context prior to starting the build. If no paths are set, the build context will not be altered.">paths</span>:
</summary><div style="margin-left:13px;">      - <span title="(string) destinationDir is the relative directory within the build directory where files copied from the image are placed.">destinationDir</span>:
</div><div style="margin-left:13px;">        <span title="(string) sourcePath is the absolute path of the file or directory inside the image to copy to the build directory.  If the source path ends in /. then the content of the directory will be copied, but the directory itself will not be created at the destination.">sourcePath</span>:
</div></details><details><summary>      <span title="(v1.LocalObjectReference) pullSecret is a reference to a secret to be used to pull the image from a registry If the image is pulled from the OpenShift registry, this field does not need to be set.">pullSecret</span>:
</summary><div style="margin-left:13px;">        <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div></details></details><details><summary>    <span title="(array) secrets represents a list of secrets and their destinations that will be used only for the build.">secrets</span>:
</summary><div style="margin-left:13px;">    - <span title="(string) destinationDir is the directory where the files from the secret should be available for the build time. For the Source build strategy, these will be injected into a container where the assemble script runs. Later, when the script finishes, all files injected will be truncated to zero length. For the Docker build strategy, these will be copied into the build directory, where the Dockerfile is located, so users can ADD or COPY them during docker build.">destinationDir</span>:
</div><details><summary>      <span title="(v1.LocalObjectReference) secret is a reference to an existing secret that you want to use in your build.">secret</span>:
</summary><div style="margin-left:13px;">        <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div></details></details><details><summary>    <span title="(v1.LocalObjectReference) sourceSecret is the name of a Secret that would be used for setting up the authentication for cloning private repository. The secret contains valid credentials for remote repository, where the data&#39;s key represent the authentication method to be used and value is the base64 encoded credentials. Supported auth methods are: ssh-privatekey.">sourceSecret</span>:
</summary><div style="margin-left:13px;">      <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div></details><div style="margin-left:13px;">    <span title="(string) type of build input to accept">type</span>:
</div></details><details><summary>  <span title="(v1.BuildStrategy) strategy defines how to perform a build.">strategy</span>:
</summary><details><summary>    <span title="(v1.CustomBuildStrategy) customStrategy holds the parameters to the Custom build strategy">customStrategy</span>:
</summary><div style="margin-left:13px;">      <span title="(string) buildAPIVersion is the requested API version for the Build object serialized and passed to the custom builder">buildAPIVersion</span>:
</div><details><summary>      <span title="(array) env contains additional environment variables you want to pass into a builder container.">env</span>:
</summary><div style="margin-left:13px;">      - <span title="(string) Name of the environment variable. Must be a C_IDENTIFIER.">name</span>:
</div><div style="margin-left:13px;">        <span title="(string) Variable references $(VAR_NAME) are expanded using the previous defined environment variables in the container and any service environment variables. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. Defaults to &#34;&#34;.">value</span>:
</div><details><summary>        <span title="(v1.EnvVarSource) Source for the environment variable&#39;s value. Cannot be used if value is not empty.">valueFrom</span>:
</summary><details><summary>          <span title="(v1.ConfigMapKeySelector) Selects a key of a ConfigMap.">configMapKeyRef</span>:
</summary><div style="margin-left:13px;">            <span title="(string) The key to select.">key</span>:
</div><div style="margin-left:13px;">            <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div><div style="margin-left:13px;">            <span title="(boolean) Specify whether the ConfigMap or it&#39;s key must be defined">optional</span>:
</div></details><details><summary>          <span title="(v1.ObjectFieldSelector) Selects a field of the pod: supports metadata.name, metadata.namespace, metadata.labels, metadata.annotations, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP.">fieldRef</span>:
</summary><div style="margin-left:13px;">            <span title="(string) Version of the schema the FieldPath is written in terms of, defaults to &#34;v1&#34;.">apiVersion</span>:
</div><div style="margin-left:13px;">            <span title="(string) Path of the field to select in the specified API version.">fieldPath</span>:
</div></details><details><summary>          <span title="(v1.ResourceFieldSelector) Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.">resourceFieldRef</span>:
</summary><div style="margin-left:13px;">            <span title="(string) Container name: required for volumes, optional for env vars">containerName</span>:
</div><div style="margin-left:13px;">            <span title="(resource.Quantity) Specifies the output format of the exposed resources, defaults to &#34;1&#34;">divisor</span>:
</div><div style="margin-left:13px;">            <span title="(string) Required: resource to select">resource</span>:
</div></details><details><summary>          <span title="(v1.SecretKeySelector) Selects a key of a secret in the pod&#39;s namespace">secretKeyRef</span>:
</summary><div style="margin-left:13px;">            <span title="(string) The key of the secret to select from.  Must be a valid secret key.">key</span>:
</div><div style="margin-left:13px;">            <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div><div style="margin-left:13px;">            <span title="(boolean) Specify whether the Secret or it&#39;s key must be defined">optional</span>:
</div></details></details></details><div style="margin-left:13px;">      <span title="(boolean) exposeDockerSocket will allow running Docker commands (and build Docker images) from inside the Docker container.">exposeDockerSocket</span>:
</div><div style="margin-left:13px;">      <span title="(boolean) forcePull describes if the controller should configure the build pod to always pull the images for the builder or only pull if it is not present locally">forcePull</span>:
</div><details><summary>      <span title="(v1.ObjectReference) from is reference to an DockerImage, ImageStreamTag, or ImageStreamImage from which the docker image should be pulled">from</span>:
</summary><div style="margin-left:13px;">        <span title="(string) API version of the referent.">apiVersion</span>:
</div><div style="margin-left:13px;">        <span title="(string) If referring to a piece of an object instead of an entire object, this string should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2]. For example, if the object reference is to a container within a pod, this would take on a value like: &#34;spec.containers{name}&#34; (where &#34;name&#34; refers to the name of the container that triggered the event) or if no container name is specified &#34;spec.containers[2]&#34; (container with index 2 in this pod). This syntax is chosen only to have some well-defined way of referencing a part of an object.">fieldPath</span>:
</div><div style="margin-left:13px;">        <span title="(string) Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds">kind</span>:
</div><div style="margin-left:13px;">        <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div><div style="margin-left:13px;">        <span title="(string) Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/">namespace</span>:
</div><div style="margin-left:13px;">        <span title="(string) Specific resourceVersion to which this reference is made, if any. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#concurrency-control-and-consistency">resourceVersion</span>:
</div><div style="margin-left:13px;">        <span title="(string) UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids">uid</span>:
</div></details><details><summary>      <span title="(v1.LocalObjectReference) pullSecret is the name of a Secret that would be used for setting up the authentication for pulling the Docker images from the private Docker registries">pullSecret</span>:
</summary><div style="margin-left:13px;">        <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div></details><details><summary>      <span title="(array) secrets is a list of additional secrets that will be included in the build pod">secrets</span>:
</summary><div style="margin-left:13px;">      - <span title="(string) mountPath is the path at which to mount the secret">mountPath</span>:
</div><details><summary>        <span title="(v1.LocalObjectReference) secretSource is a reference to the secret">secretSource</span>:
</summary><div style="margin-left:13px;">          <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div></details></details></details><details><summary>    <span title="(v1.DockerBuildStrategy) dockerStrategy holds the parameters to the Docker build strategy.">dockerStrategy</span>:
</summary><details><summary>      <span title="(array) buildArgs contains build arguments that will be resolved in the Dockerfile.  See https://docs.docker.com/engine/reference/builder/#/arg for more details.">buildArgs</span>:
</summary><div style="margin-left:13px;">      - <span title="(string) Name of the environment variable. Must be a C_IDENTIFIER.">name</span>:
</div><div style="margin-left:13px;">        <span title="(string) Variable references $(VAR_NAME) are expanded using the previous defined environment variables in the container and any service environment variables. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. Defaults to &#34;&#34;.">value</span>:
</div><details><summary>        <span title="(v1.EnvVarSource) Source for the environment variable&#39;s value. Cannot be used if value is not empty.">valueFrom</span>:
</summary><details><summary>          <span title="(v1.ConfigMapKeySelector) Selects a key of a ConfigMap.">configMapKeyRef</span>:
</summary><div style="margin-left:13px;">            <span title="(string) The key to select.">key</span>:
</div><div style="margin-left:13px;">            <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div><div style="margin-left:13px;">            <span title="(boolean) Specify whether the ConfigMap or it&#39;s key must be defined">optional</span>:
</div></details><details><summary>          <span title="(v1.ObjectFieldSelector) Selects a field of the pod: supports metadata.name, metadata.namespace, metadata.labels, metadata.annotations, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP.">fieldRef</span>:
</summary><div style="margin-left:13px;">            <span title="(string) Version of the schema the FieldPath is written in terms of, defaults to &#34;v1&#34;.">apiVersion</span>:
</div><div style="margin-left:13px;">            <span title="(string) Path of the field to select in the specified API version.">fieldPath</span>:
</div></details><details><summary>          <span title="(v1.ResourceFieldSelector) Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.">resourceFieldRef</span>:
</summary><div style="margin-left:13px;">            <span title="(string) Container name: required for volumes, optional for env vars">containerName</span>:
</div><div style="margin-left:13px;">            <span title="(resource.Quantity) Specifies the output format of the exposed resources, defaults to &#34;1&#34;">divisor</span>:
</div><div style="margin-left:13px;">            <span title="(string) Required: resource to select">resource</span>:
</div></details><details><summary>          <span title="(v1.SecretKeySelector) Selects a key of a secret in the pod&#39;s namespace">secretKeyRef</span>:
</summary><div style="margin-left:13px;">            <span title="(string) The key of the secret to select from.  Must be a valid secret key.">key</span>:
</div><div style="margin-left:13px;">            <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div><div style="margin-left:13px;">            <span title="(boolean) Specify whether the Secret or it&#39;s key must be defined">optional</span>:
</div></details></details></details><div style="margin-left:13px;">      <span title="(string) dockerfilePath is the path of the Dockerfile that will be used to build the Docker image, relative to the root of the context (contextDir).">dockerfilePath</span>:
</div><details><summary>      <span title="(array) env contains additional environment variables you want to pass into a builder container.">env</span>:
</summary><div style="margin-left:13px;">      - <span title="(string) Name of the environment variable. Must be a C_IDENTIFIER.">name</span>:
</div><div style="margin-left:13px;">        <span title="(string) Variable references $(VAR_NAME) are expanded using the previous defined environment variables in the container and any service environment variables. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. Defaults to &#34;&#34;.">value</span>:
</div><details><summary>        <span title="(v1.EnvVarSource) Source for the environment variable&#39;s value. Cannot be used if value is not empty.">valueFrom</span>:
</summary><details><summary>          <span title="(v1.ConfigMapKeySelector) Selects a key of a ConfigMap.">configMapKeyRef</span>:
</summary><div style="margin-left:13px;">            <span title="(string) The key to select.">key</span>:
</div><div style="margin-left:13px;">            <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div><div style="margin-left:13px;">            <span title="(boolean) Specify whether the ConfigMap or it&#39;s key must be defined">optional</span>:
</div></details><details><summary>          <span title="(v1.ObjectFieldSelector) Selects a field of the pod: supports metadata.name, metadata.namespace, metadata.labels, metadata.annotations, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP.">fieldRef</span>:
</summary><div style="margin-left:13px;">            <span title="(string) Version of the schema the FieldPath is written in terms of, defaults to &#34;v1&#34;.">apiVersion</span>:
</div><div style="margin-left:13px;">            <span title="(string) Path of the field to select in the specified API version.">fieldPath</span>:
</div></details><details><summary>          <span title="(v1.ResourceFieldSelector) Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.">resourceFieldRef</span>:
</summary><div style="margin-left:13px;">            <span title="(string) Container name: required for volumes, optional for env vars">containerName</span>:
</div><div style="margin-left:13px;">            <span title="(resource.Quantity) Specifies the output format of the exposed resources, defaults to &#34;1&#34;">divisor</span>:
</div><div style="margin-left:13px;">            <span title="(string) Required: resource to select">resource</span>:
</div></details><details><summary>          <span title="(v1.SecretKeySelector) Selects a key of a secret in the pod&#39;s namespace">secretKeyRef</span>:
</summary><div style="margin-left:13px;">            <span title="(string) The key of the secret to select from.  Must be a valid secret key.">key</span>:
</div><div style="margin-left:13px;">            <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div><div style="margin-left:13px;">            <span title="(boolean) Specify whether the Secret or it&#39;s key must be defined">optional</span>:
</div></details></details></details><div style="margin-left:13px;">      <span title="(boolean) forcePull describes if the builder should pull the images from registry prior to building.">forcePull</span>:
</div><details><summary>      <span title="(v1.ObjectReference) from is reference to an DockerImage, ImageStreamTag, or ImageStreamImage from which the docker image should be pulled the resulting image will be used in the FROM line of the Dockerfile for this build.">from</span>:
</summary><div style="margin-left:13px;">        <span title="(string) API version of the referent.">apiVersion</span>:
</div><div style="margin-left:13px;">        <span title="(string) If referring to a piece of an object instead of an entire object, this string should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2]. For example, if the object reference is to a container within a pod, this would take on a value like: &#34;spec.containers{name}&#34; (where &#34;name&#34; refers to the name of the container that triggered the event) or if no container name is specified &#34;spec.containers[2]&#34; (container with index 2 in this pod). This syntax is chosen only to have some well-defined way of referencing a part of an object.">fieldPath</span>:
</div><div style="margin-left:13px;">        <span title="(string) Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds">kind</span>:
</div><div style="margin-left:13px;">        <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div><div style="margin-left:13px;">        <span title="(string) Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/">namespace</span>:
</div><div style="margin-left:13px;">        <span title="(string) Specific resourceVersion to which this reference is made, if any. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#concurrency-control-and-consistency">resourceVersion</span>:
</div><div style="margin-left:13px;">        <span title="(string) UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids">uid</span>:
</div></details><div style="margin-left:13px;">      <span title="(string) imageOptimizationPolicy describes what optimizations the system can use when building images to reduce the final size or time spent building the image. The default policy is &#39;None&#39; which means the final build image will be equivalent to an image created by the Docker build API. The experimental policy &#39;SkipLayers&#39; will avoid commiting new layers in between each image step, and will fail if the Dockerfile cannot provide compatibility with the &#39;None&#39; policy. An additional experimental policy &#39;SkipLayersAndWarn&#39; is the same as &#39;SkipLayers&#39; but simply warns if compatibility cannot be preserved.">imageOptimizationPolicy</span>:
</div><div style="margin-left:13px;">      <span title="(boolean) noCache if set to true indicates that the docker build must be executed with the --no-cache=true flag">noCache</span>:
</div><details><summary>      <span title="(v1.LocalObjectReference) pullSecret is the name of a Secret that would be used for setting up the authentication for pulling the Docker images from the private Docker registries">pullSecret</span>:
</summary><div style="margin-left:13px;">        <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div></details></details><details><summary>    <span title="(v1.JenkinsPipelineBuildStrategy) JenkinsPipelineStrategy holds the parameters to the Jenkins Pipeline build strategy.">jenkinsPipelineStrategy</span>:
</summary><details><summary>      <span title="(array) env contains additional environment variables you want to pass into a build pipeline.">env</span>:
</summary><div style="margin-left:13px;">      - <span title="(string) Name of the environment variable. Must be a C_IDENTIFIER.">name</span>:
</div><div style="margin-left:13px;">        <span title="(string) Variable references $(VAR_NAME) are expanded using the previous defined environment variables in the container and any service environment variables. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. Defaults to &#34;&#34;.">value</span>:
</div><details><summary>        <span title="(v1.EnvVarSource) Source for the environment variable&#39;s value. Cannot be used if value is not empty.">valueFrom</span>:
</summary><details><summary>          <span title="(v1.ConfigMapKeySelector) Selects a key of a ConfigMap.">configMapKeyRef</span>:
</summary><div style="margin-left:13px;">            <span title="(string) The key to select.">key</span>:
</div><div style="margin-left:13px;">            <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div><div style="margin-left:13px;">            <span title="(boolean) Specify whether the ConfigMap or it&#39;s key must be defined">optional</span>:
</div></details><details><summary>          <span title="(v1.ObjectFieldSelector) Selects a field of the pod: supports metadata.name, metadata.namespace, metadata.labels, metadata.annotations, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP.">fieldRef</span>:
</summary><div style="margin-left:13px;">            <span title="(string) Version of the schema the FieldPath is written in terms of, defaults to &#34;v1&#34;.">apiVersion</span>:
</div><div style="margin-left:13px;">            <span title="(string) Path of the field to select in the specified API version.">fieldPath</span>:
</div></details><details><summary>          <span title="(v1.ResourceFieldSelector) Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.">resourceFieldRef</span>:
</summary><div style="margin-left:13px;">            <span title="(string) Container name: required for volumes, optional for env vars">containerName</span>:
</div><div style="margin-left:13px;">            <span title="(resource.Quantity) Specifies the output format of the exposed resources, defaults to &#34;1&#34;">divisor</span>:
</div><div style="margin-left:13px;">            <span title="(string) Required: resource to select">resource</span>:
</div></details><details><summary>          <span title="(v1.SecretKeySelector) Selects a key of a secret in the pod&#39;s namespace">secretKeyRef</span>:
</summary><div style="margin-left:13px;">            <span title="(string) The key of the secret to select from.  Must be a valid secret key.">key</span>:
</div><div style="margin-left:13px;">            <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div><div style="margin-left:13px;">            <span title="(boolean) Specify whether the Secret or it&#39;s key must be defined">optional</span>:
</div></details></details></details><div style="margin-left:13px;">      <span title="(string) Jenkinsfile defines the optional raw contents of a Jenkinsfile which defines a Jenkins pipeline build.">jenkinsfile</span>:
</div><div style="margin-left:13px;">      <span title="(string) JenkinsfilePath is the optional path of the Jenkinsfile that will be used to configure the pipeline relative to the root of the context (contextDir). If both JenkinsfilePath &amp; Jenkinsfile are both not specified, this defaults to Jenkinsfile in the root of the specified contextDir.">jenkinsfilePath</span>:
</div></details><details><summary>    <span title="(v1.SourceBuildStrategy) sourceStrategy holds the parameters to the Source build strategy.">sourceStrategy</span>:
</summary><details><summary>      <span title="(array) env contains additional environment variables you want to pass into a builder container.">env</span>:
</summary><div style="margin-left:13px;">      - <span title="(string) Name of the environment variable. Must be a C_IDENTIFIER.">name</span>:
</div><div style="margin-left:13px;">        <span title="(string) Variable references $(VAR_NAME) are expanded using the previous defined environment variables in the container and any service environment variables. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. Defaults to &#34;&#34;.">value</span>:
</div><details><summary>        <span title="(v1.EnvVarSource) Source for the environment variable&#39;s value. Cannot be used if value is not empty.">valueFrom</span>:
</summary><details><summary>          <span title="(v1.ConfigMapKeySelector) Selects a key of a ConfigMap.">configMapKeyRef</span>:
</summary><div style="margin-left:13px;">            <span title="(string) The key to select.">key</span>:
</div><div style="margin-left:13px;">            <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div><div style="margin-left:13px;">            <span title="(boolean) Specify whether the ConfigMap or it&#39;s key must be defined">optional</span>:
</div></details><details><summary>          <span title="(v1.ObjectFieldSelector) Selects a field of the pod: supports metadata.name, metadata.namespace, metadata.labels, metadata.annotations, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP.">fieldRef</span>:
</summary><div style="margin-left:13px;">            <span title="(string) Version of the schema the FieldPath is written in terms of, defaults to &#34;v1&#34;.">apiVersion</span>:
</div><div style="margin-left:13px;">            <span title="(string) Path of the field to select in the specified API version.">fieldPath</span>:
</div></details><details><summary>          <span title="(v1.ResourceFieldSelector) Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.">resourceFieldRef</span>:
</summary><div style="margin-left:13px;">            <span title="(string) Container name: required for volumes, optional for env vars">containerName</span>:
</div><div style="margin-left:13px;">            <span title="(resource.Quantity) Specifies the output format of the exposed resources, defaults to &#34;1&#34;">divisor</span>:
</div><div style="margin-left:13px;">            <span title="(string) Required: resource to select">resource</span>:
</div></details><details><summary>          <span title="(v1.SecretKeySelector) Selects a key of a secret in the pod&#39;s namespace">secretKeyRef</span>:
</summary><div style="margin-left:13px;">            <span title="(string) The key of the secret to select from.  Must be a valid secret key.">key</span>:
</div><div style="margin-left:13px;">            <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div><div style="margin-left:13px;">            <span title="(boolean) Specify whether the Secret or it&#39;s key must be defined">optional</span>:
</div></details></details></details><div style="margin-left:13px;">      <span title="(boolean) forcePull describes if the builder should pull the images from registry prior to building.">forcePull</span>:
</div><details><summary>      <span title="(v1.ObjectReference) from is reference to an DockerImage, ImageStreamTag, or ImageStreamImage from which the docker image should be pulled">from</span>:
</summary><div style="margin-left:13px;">        <span title="(string) API version of the referent.">apiVersion</span>:
</div><div style="margin-left:13px;">        <span title="(string) If referring to a piece of an object instead of an entire object, this string should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2]. For example, if the object reference is to a container within a pod, this would take on a value like: &#34;spec.containers{name}&#34; (where &#34;name&#34; refers to the name of the container that triggered the event) or if no container name is specified &#34;spec.containers[2]&#34; (container with index 2 in this pod). This syntax is chosen only to have some well-defined way of referencing a part of an object.">fieldPath</span>:
</div><div style="margin-left:13px;">        <span title="(string) Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds">kind</span>:
</div><div style="margin-left:13px;">        <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div><div style="margin-left:13px;">        <span title="(string) Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/">namespace</span>:
</div><div style="margin-left:13px;">        <span title="(string) Specific resourceVersion to which this reference is made, if any. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#concurrency-control-and-consistency">resourceVersion</span>:
</div><div style="margin-left:13px;">        <span title="(string) UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids">uid</span>:
</div></details><div style="margin-left:13px;">      <span title="(boolean) incremental flag forces the Source build to do incremental builds if true.">incremental</span>:
</div><details><summary>      <span title="(v1.LocalObjectReference) pullSecret is the name of a Secret that would be used for setting up the authentication for pulling the Docker images from the private Docker registries">pullSecret</span>:
</summary><div style="margin-left:13px;">        <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div></details><div style="margin-left:13px;">      <span title="(string) scripts is the location of Source scripts">scripts</span>:
</div></details><div style="margin-left:13px;">    <span title="(string) type is the kind of build strategy.">type</span>:
</div></details><div style="margin-left:13px;">  <span title="(integer) successfulBuildsHistoryLimit is the number of old successful builds to retain. If not specified, all successful builds are retained.">successfulBuildsHistoryLimit</span>:
</div><details><summary>  <span title="(array) triggers determine how new Builds can be launched from a BuildConfig. If no triggers are defined, a new build can only occur as a result of an explicit client build creation.">triggers</span>:
</summary><details><summary>  - <span title="(v1.WebHookTrigger) BitbucketWebHook contains the parameters for a Bitbucket webhook type of trigger">bitbucket</span>:
</summary><div style="margin-left:13px;">  -   <span title="(boolean) allowEnv determines whether the webhook can set environment variables; can only be set to true for GenericWebHook.">allowEnv</span>:
</div><div style="margin-left:13px;">      <span title="(string) secret used to validate requests. Deprecated: use SecretReference instead.">secret</span>:
</div><details><summary>      <span title="(v1.SecretLocalReference) secretReference is a reference to a secret in the same namespace, containing the value to be validated when the webhook is invoked. The secret being referenced must contain a key named &#34;WebHookSecretKey&#34;, the value of which will be checked against the value supplied in the webhook invocation.">secretReference</span>:
</summary><div style="margin-left:13px;">        <span title="(string) Name is the name of the resource in the same namespace being referenced">name</span>:
</div></details></details><details><summary>    <span title="(v1.WebHookTrigger) generic contains the parameters for a Generic webhook type of trigger">generic</span>:
</summary><div style="margin-left:13px;">      <span title="(boolean) allowEnv determines whether the webhook can set environment variables; can only be set to true for GenericWebHook.">allowEnv</span>:
</div><div style="margin-left:13px;">      <span title="(string) secret used to validate requests. Deprecated: use SecretReference instead.">secret</span>:
</div><details><summary>      <span title="(v1.SecretLocalReference) secretReference is a reference to a secret in the same namespace, containing the value to be validated when the webhook is invoked. The secret being referenced must contain a key named &#34;WebHookSecretKey&#34;, the value of which will be checked against the value supplied in the webhook invocation.">secretReference</span>:
</summary><div style="margin-left:13px;">        <span title="(string) Name is the name of the resource in the same namespace being referenced">name</span>:
</div></details></details><details><summary>    <span title="(v1.WebHookTrigger) github contains the parameters for a GitHub webhook type of trigger">github</span>:
</summary><div style="margin-left:13px;">      <span title="(boolean) allowEnv determines whether the webhook can set environment variables; can only be set to true for GenericWebHook.">allowEnv</span>:
</div><div style="margin-left:13px;">      <span title="(string) secret used to validate requests. Deprecated: use SecretReference instead.">secret</span>:
</div><details><summary>      <span title="(v1.SecretLocalReference) secretReference is a reference to a secret in the same namespace, containing the value to be validated when the webhook is invoked. The secret being referenced must contain a key named &#34;WebHookSecretKey&#34;, the value of which will be checked against the value supplied in the webhook invocation.">secretReference</span>:
</summary><div style="margin-left:13px;">        <span title="(string) Name is the name of the resource in the same namespace being referenced">name</span>:
</div></details></details><details><summary>    <span title="(v1.WebHookTrigger) GitLabWebHook contains the parameters for a GitLab webhook type of trigger">gitlab</span>:
</summary><div style="margin-left:13px;">      <span title="(boolean) allowEnv determines whether the webhook can set environment variables; can only be set to true for GenericWebHook.">allowEnv</span>:
</div><div style="margin-left:13px;">      <span title="(string) secret used to validate requests. Deprecated: use SecretReference instead.">secret</span>:
</div><details><summary>      <span title="(v1.SecretLocalReference) secretReference is a reference to a secret in the same namespace, containing the value to be validated when the webhook is invoked. The secret being referenced must contain a key named &#34;WebHookSecretKey&#34;, the value of which will be checked against the value supplied in the webhook invocation.">secretReference</span>:
</summary><div style="margin-left:13px;">        <span title="(string) Name is the name of the resource in the same namespace being referenced">name</span>:
</div></details></details><details><summary>    <span title="(v1.ImageChangeTrigger) imageChange contains parameters for an ImageChange type of trigger">imageChange</span>:
</summary><details><summary>      <span title="(v1.ObjectReference) from is a reference to an ImageStreamTag that will trigger a build when updated It is optional. If no From is specified, the From image from the build strategy will be used. Only one ImageChangeTrigger with an empty From reference is allowed in a build configuration.">from</span>:
</summary><div style="margin-left:13px;">        <span title="(string) API version of the referent.">apiVersion</span>:
</div><div style="margin-left:13px;">        <span title="(string) If referring to a piece of an object instead of an entire object, this string should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2]. For example, if the object reference is to a container within a pod, this would take on a value like: &#34;spec.containers{name}&#34; (where &#34;name&#34; refers to the name of the container that triggered the event) or if no container name is specified &#34;spec.containers[2]&#34; (container with index 2 in this pod). This syntax is chosen only to have some well-defined way of referencing a part of an object.">fieldPath</span>:
</div><div style="margin-left:13px;">        <span title="(string) Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds">kind</span>:
</div><div style="margin-left:13px;">        <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div><div style="margin-left:13px;">        <span title="(string) Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/">namespace</span>:
</div><div style="margin-left:13px;">        <span title="(string) Specific resourceVersion to which this reference is made, if any. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#concurrency-control-and-consistency">resourceVersion</span>:
</div><div style="margin-left:13px;">        <span title="(string) UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids">uid</span>:
</div></details><div style="margin-left:13px;">      <span title="(string) lastTriggeredImageID is used internally by the ImageChangeController to save last used image ID for build">lastTriggeredImageID</span>:
</div></details><div style="margin-left:13px;">    <span title="(string) type is the type of build trigger">type</span>:
</div></details></details><details><summary><span title="(v1.BuildConfigStatus) status holds any relevant information about a build config">status</span>:
</summary><div style="margin-left:13px;">  <span title="(integer) lastVersion is used to inform about number of last triggered build.">lastVersion</span>:
</div></details>
</pre>
++++

== Operations

[[Post-oapi-v1-buildconfigs]]
=== Create a BuildConfig
Create a BuildConfig

==== HTTP request
----
POST /oapi/v1/buildconfigs HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
Content-Type: application/json'

{
  "kind": "BuildConfig",
  "apiVersion": "v1",
  ...
}

----

==== Curl request
----
$ curl -k \
    -X POST \
    -d @- \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
    https://$ENDPOINT/oapi/v1/buildconfigs <<'EOF'
{
  "kind": "BuildConfig",
  "apiVersion": "v1",
  ...
}
EOF
----

==== HTTP body
[cols="1,5", options="header"]
|===
|Parameter|Schema
|body|v1.BuildConfig
|===

==== Query parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|pretty|If 'true', then the output is pretty printed.
|===

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.BuildConfig
|201 Created|v1.BuildConfig
|202 Accepted|v1.BuildConfig
|401 Unauthorized|
|===

==== Consumes

* \*/*

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Post-oapi-v1-namespaces-namespace-buildconfigs]]
=== Create a BuildConfig in a namespace
Create a BuildConfig

==== HTTP request
----
POST /oapi/v1/namespaces/$NAMESPACE/buildconfigs HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
Content-Type: application/json'

{
  "kind": "BuildConfig",
  "apiVersion": "v1",
  ...
}

----

==== Curl request
----
$ curl -k \
    -X POST \
    -d @- \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
    https://$ENDPOINT/oapi/v1/namespaces/$NAMESPACE/buildconfigs <<'EOF'
{
  "kind": "BuildConfig",
  "apiVersion": "v1",
  ...
}
EOF
----

==== HTTP body
[cols="1,5", options="header"]
|===
|Parameter|Schema
|body|v1.BuildConfig
|===

==== Path parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|namespace|object name and auth scope, such as for teams and projects
|===

==== Query parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|pretty|If 'true', then the output is pretty printed.
|===

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.BuildConfig
|201 Created|v1.BuildConfig
|202 Accepted|v1.BuildConfig
|401 Unauthorized|
|===

==== Consumes

* \*/*

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-oapi-v1-namespaces-namespace-buildconfigs-name]]
=== Get a BuildConfig in a namespace
Read the specified BuildConfig

==== HTTP request
----
GET /oapi/v1/namespaces/$NAMESPACE/buildconfigs/$NAME HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/oapi/v1/namespaces/$NAMESPACE/buildconfigs/$NAME
----

==== Path parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|name|name of the BuildConfig
|namespace|object name and auth scope, such as for teams and projects
|===

==== Query parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|pretty|If 'true', then the output is pretty printed.
|exact|Should the export be exact.  Exact export maintains cluster-specific fields like 'Namespace'.
|export|Should this value be exported.  Export strips fields that a user can not specify.
|===

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.BuildConfig
|401 Unauthorized|
|===

==== Consumes

* \*/*

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Get-oapi-v1-buildconfigs]]
=== Get all BuildConfigs
List or watch objects of kind BuildConfig

==== HTTP request
----
GET /oapi/v1/buildconfigs HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/oapi/v1/buildconfigs
----

==== Query parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|pretty|If 'true', then the output is pretty printed.
|continue|The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server the server will respond with a 410 ResourceExpired error indicating the client must restart their list without the continue field. This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications.
|fieldSelector|A selector to restrict the list of returned objects by their fields. Defaults to everything.
|includeUninitialized|If true, partially initialized resources are included in the response.
|labelSelector|A selector to restrict the list of returned objects by their labels. Defaults to everything.
|limit|limit is a maximum number of responses to return for a list call. If more items exist, the server will set the `continue` field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.

The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned.
|resourceVersion|When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it's 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv.
|timeoutSeconds|Timeout for the list/watch call.
|watch|Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion.
|===

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.BuildConfigList
|401 Unauthorized|
|===

==== Consumes

* \*/*

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf
* application/json;stream=watch
* application/vnd.kubernetes.protobuf;stream=watch


[[Get-oapi-v1-namespaces-namespace-buildconfigs]]
=== Get all BuildConfigs in a namespace
List or watch objects of kind BuildConfig

==== HTTP request
----
GET /oapi/v1/namespaces/$NAMESPACE/buildconfigs HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/oapi/v1/namespaces/$NAMESPACE/buildconfigs
----

==== Path parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|namespace|object name and auth scope, such as for teams and projects
|===

==== Query parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|pretty|If 'true', then the output is pretty printed.
|continue|The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server the server will respond with a 410 ResourceExpired error indicating the client must restart their list without the continue field. This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications.
|fieldSelector|A selector to restrict the list of returned objects by their fields. Defaults to everything.
|includeUninitialized|If true, partially initialized resources are included in the response.
|labelSelector|A selector to restrict the list of returned objects by their labels. Defaults to everything.
|limit|limit is a maximum number of responses to return for a list call. If more items exist, the server will set the `continue` field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.

The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned.
|resourceVersion|When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it's 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv.
|timeoutSeconds|Timeout for the list/watch call.
|watch|Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion.
|===

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.BuildConfigList
|401 Unauthorized|
|===

==== Consumes

* \*/*

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf
* application/json;stream=watch
* application/vnd.kubernetes.protobuf;stream=watch


[[Get-oapi-v1-watch-namespaces-namespace-buildconfigs-name]]
=== Watch a BuildConfig in a namespace
Watch changes to an object of kind BuildConfig

==== HTTP request
----
GET /oapi/v1/watch/namespaces/$NAMESPACE/buildconfigs/$NAME HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/oapi/v1/watch/namespaces/$NAMESPACE/buildconfigs/$NAME
----

==== Path parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|name|name of the BuildConfig
|namespace|object name and auth scope, such as for teams and projects
|===

==== Query parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|continue|The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server the server will respond with a 410 ResourceExpired error indicating the client must restart their list without the continue field. This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications.
|fieldSelector|A selector to restrict the list of returned objects by their fields. Defaults to everything.
|includeUninitialized|If true, partially initialized resources are included in the response.
|labelSelector|A selector to restrict the list of returned objects by their labels. Defaults to everything.
|limit|limit is a maximum number of responses to return for a list call. If more items exist, the server will set the `continue` field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.

The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned.
|pretty|If 'true', then the output is pretty printed.
|resourceVersion|When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it's 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv.
|timeoutSeconds|Timeout for the list/watch call.
|watch|Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion.
|===

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.WatchEvent
|401 Unauthorized|
|===

==== Consumes

* \*/*

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf
* application/json;stream=watch
* application/vnd.kubernetes.protobuf;stream=watch


[[Get-oapi-v1-watch-buildconfigs]]
=== Watch all BuildConfigs
Watch individual changes to a list of BuildConfig

==== HTTP request
----
GET /oapi/v1/watch/buildconfigs HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/oapi/v1/watch/buildconfigs
----

==== Query parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|continue|The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server the server will respond with a 410 ResourceExpired error indicating the client must restart their list without the continue field. This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications.
|fieldSelector|A selector to restrict the list of returned objects by their fields. Defaults to everything.
|includeUninitialized|If true, partially initialized resources are included in the response.
|labelSelector|A selector to restrict the list of returned objects by their labels. Defaults to everything.
|limit|limit is a maximum number of responses to return for a list call. If more items exist, the server will set the `continue` field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.

The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned.
|pretty|If 'true', then the output is pretty printed.
|resourceVersion|When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it's 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv.
|timeoutSeconds|Timeout for the list/watch call.
|watch|Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion.
|===

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.WatchEvent
|401 Unauthorized|
|===

==== Consumes

* \*/*

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf
* application/json;stream=watch
* application/vnd.kubernetes.protobuf;stream=watch


[[Get-oapi-v1-watch-namespaces-namespace-buildconfigs]]
=== Watch all BuildConfigs in a namespace
Watch individual changes to a list of BuildConfig

==== HTTP request
----
GET /oapi/v1/watch/namespaces/$NAMESPACE/buildconfigs HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/oapi/v1/watch/namespaces/$NAMESPACE/buildconfigs
----

==== Path parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|namespace|object name and auth scope, such as for teams and projects
|===

==== Query parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|continue|The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server the server will respond with a 410 ResourceExpired error indicating the client must restart their list without the continue field. This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications.
|fieldSelector|A selector to restrict the list of returned objects by their fields. Defaults to everything.
|includeUninitialized|If true, partially initialized resources are included in the response.
|labelSelector|A selector to restrict the list of returned objects by their labels. Defaults to everything.
|limit|limit is a maximum number of responses to return for a list call. If more items exist, the server will set the `continue` field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.

The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned.
|pretty|If 'true', then the output is pretty printed.
|resourceVersion|When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it's 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv.
|timeoutSeconds|Timeout for the list/watch call.
|watch|Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion.
|===

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.WatchEvent
|401 Unauthorized|
|===

==== Consumes

* \*/*

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf
* application/json;stream=watch
* application/vnd.kubernetes.protobuf;stream=watch


[[Put-oapi-v1-namespaces-namespace-buildconfigs-name]]
=== Update a BuildConfig in a namespace
Replace the specified BuildConfig

==== HTTP request
----
PUT /oapi/v1/namespaces/$NAMESPACE/buildconfigs/$NAME HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
Content-Type: application/json'

{
  "kind": "BuildConfig",
  "apiVersion": "v1",
  ...
}

----

==== Curl request
----
$ curl -k \
    -X PUT \
    -d @- \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
    https://$ENDPOINT/oapi/v1/namespaces/$NAMESPACE/buildconfigs/$NAME <<'EOF'
{
  "kind": "BuildConfig",
  "apiVersion": "v1",
  ...
}
EOF
----

==== HTTP body
[cols="1,5", options="header"]
|===
|Parameter|Schema
|body|v1.BuildConfig
|===

==== Path parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|name|name of the BuildConfig
|namespace|object name and auth scope, such as for teams and projects
|===

==== Query parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|pretty|If 'true', then the output is pretty printed.
|===

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.BuildConfig
|201 Created|v1.BuildConfig
|401 Unauthorized|
|===

==== Consumes

* \*/*

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Patch-oapi-v1-namespaces-namespace-buildconfigs-name]]
=== Patch a BuildConfig in a namespace
Partially update the specified BuildConfig

==== HTTP request
----
PATCH /oapi/v1/namespaces/$NAMESPACE/buildconfigs/$NAME HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
Content-Type: application/json-patch+json'

{
  ...
}

----

==== Curl request
----
$ curl -k \
    -X PATCH \
    -d @- \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json-patch+json' \
    https://$ENDPOINT/oapi/v1/namespaces/$NAMESPACE/buildconfigs/$NAME <<'EOF'
{
  ...
}
EOF
----

==== HTTP body
[cols="1,5", options="header"]
|===
|Parameter|Schema
|body|v1.Patch
|===

==== Path parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|name|name of the BuildConfig
|namespace|object name and auth scope, such as for teams and projects
|===

==== Query parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|pretty|If 'true', then the output is pretty printed.
|===

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.BuildConfig
|401 Unauthorized|
|===

==== Consumes

* application/json-patch+json
* application/merge-patch+json
* application/strategic-merge-patch+json

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Delete-oapi-v1-namespaces-namespace-buildconfigs-name]]
=== Delete a BuildConfig in a namespace
Delete a BuildConfig

==== HTTP request
----
DELETE /oapi/v1/namespaces/$NAMESPACE/buildconfigs/$NAME HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
Content-Type: application/json'

{
  ...
}

----

==== Curl request
----
$ curl -k \
    -X DELETE \
    -d @- \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
    https://$ENDPOINT/oapi/v1/namespaces/$NAMESPACE/buildconfigs/$NAME <<'EOF'
{
  ...
}
EOF
----

==== HTTP body
[cols="1,5", options="header"]
|===
|Parameter|Schema
|body|v1.DeleteOptions
|===

==== Path parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|name|name of the BuildConfig
|namespace|object name and auth scope, such as for teams and projects
|===

==== Query parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|pretty|If 'true', then the output is pretty printed.
|gracePeriodSeconds|The duration in seconds before the object should be deleted. Value must be non-negative integer. The value zero indicates delete immediately. If this value is nil, the default grace period for the specified type will be used. Defaults to a per object value if not specified. zero means delete immediately.
|orphanDependents|Deprecated: please use the PropagationPolicy, this field will be deprecated in 1.7. Should the dependent objects be orphaned. If true/false, the "orphan" finalizer will be added to/removed from the object's finalizers list. Either this field or PropagationPolicy may be set, but not both.
|propagationPolicy|Whether and how garbage collection will be performed. Either this field or OrphanDependents may be set, but not both. The default policy is decided by the existing finalizer set in the metadata.finalizers and the resource-specific default policy. Acceptable values are: 'Orphan' - orphan the dependents; 'Background' - allow the garbage collector to delete the dependents in the background; 'Foreground' - a cascading policy that deletes all dependents in the foreground.
|===

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.Status
|401 Unauthorized|
|===

==== Consumes

* \*/*

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Delete-oapi-v1-namespaces-namespace-buildconfigs]]
=== Delete all BuildConfigs in a namespace
Delete collection of BuildConfig

==== HTTP request
----
DELETE /oapi/v1/namespaces/$NAMESPACE/buildconfigs HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -X DELETE \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/oapi/v1/namespaces/$NAMESPACE/buildconfigs
----

==== Path parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|namespace|object name and auth scope, such as for teams and projects
|===

==== Query parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|pretty|If 'true', then the output is pretty printed.
|continue|The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server the server will respond with a 410 ResourceExpired error indicating the client must restart their list without the continue field. This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications.
|fieldSelector|A selector to restrict the list of returned objects by their fields. Defaults to everything.
|includeUninitialized|If true, partially initialized resources are included in the response.
|labelSelector|A selector to restrict the list of returned objects by their labels. Defaults to everything.
|limit|limit is a maximum number of responses to return for a list call. If more items exist, the server will set the `continue` field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.

The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned.
|resourceVersion|When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it's 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv.
|timeoutSeconds|Timeout for the list/watch call.
|watch|Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion.
|===

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.Status
|401 Unauthorized|
|===

==== Consumes

* \*/*

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Post-oapi-v1-namespaces-namespace-buildconfigs-name-instantiate]]
=== Create instantiate of a BuildConfig in a namespace
Create instantiate of a BuildConfig

==== HTTP request
----
POST /oapi/v1/namespaces/$NAMESPACE/buildconfigs/$NAME/instantiate HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
Content-Type: application/json'

{
  "kind": "BuildRequest",
  "apiVersion": "v1",
  ...
}

----

==== Curl request
----
$ curl -k \
    -X POST \
    -d @- \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
    https://$ENDPOINT/oapi/v1/namespaces/$NAMESPACE/buildconfigs/$NAME/instantiate <<'EOF'
{
  "kind": "BuildRequest",
  "apiVersion": "v1",
  ...
}
EOF
----

==== HTTP body
[cols="1,5", options="header"]
|===
|Parameter|Schema
|body|v1.BuildRequest
|===

==== Path parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|name|name of the BuildRequest
|namespace|object name and auth scope, such as for teams and projects
|===

==== Query parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|pretty|If 'true', then the output is pretty printed.
|===

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.Build
|201 Created|v1.Build
|202 Accepted|v1.Build
|401 Unauthorized|
|===

==== Consumes

* \*/*

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Post-oapi-v1-namespaces-namespace-buildconfigs-name-instantiatebinary]]
=== Create instantiatebinary of a BuildConfig in a namespace
Connect POST requests to instantiatebinary of BuildConfig

==== HTTP request
----
POST /oapi/v1/namespaces/$NAMESPACE/buildconfigs/$NAME/instantiatebinary HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -X POST \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/oapi/v1/namespaces/$NAMESPACE/buildconfigs/$NAME/instantiatebinary
----

==== Path parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|name|name of the BinaryBuildRequestOptions
|namespace|object name and auth scope, such as for teams and projects
|===

==== Query parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|asFile|asFile determines if the binary should be created as a file within the source rather than extracted as an archive
|revision.authorEmail|revision.authorEmail of the source control user
|revision.authorName|revision.authorName of the source control user
|revision.commit|revision.commit is the value identifying a specific commit
|revision.committerEmail|revision.committerEmail of the source control user
|revision.committerName|revision.committerName of the source control user
|revision.message|revision.message is the description of a specific commit
|===

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.Build
|401 Unauthorized|
|===

==== Consumes

* \*/*

==== Produces

* \*/*


[[Post-oapi-v1-namespaces-namespace-buildconfigs-name-webhooks]]
=== Create webhooks of a BuildConfig in a namespace
Connect POST requests to webhooks of BuildConfig

==== HTTP request
----
POST /oapi/v1/namespaces/$NAMESPACE/buildconfigs/$NAME/webhooks HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -X POST \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/oapi/v1/namespaces/$NAMESPACE/buildconfigs/$NAME/webhooks
----

==== Path parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|name|name of the Build
|namespace|object name and auth scope, such as for teams and projects
|===

==== Query parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|path|Path is the URL path to use for the current proxy request to pod.
|===

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|string
|401 Unauthorized|
|===

==== Consumes

* \*/*

==== Produces

* \*/*


[[Post-oapi-v1-namespaces-namespace-buildconfigs-name-webhooks-path]]
=== Create webhooks/{path} of a BuildConfig in a namespace
Connect POST requests to webhooks of BuildConfig

==== HTTP request
----
POST /oapi/v1/namespaces/$NAMESPACE/buildconfigs/$NAME/webhooks/$PATH HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -X POST \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/oapi/v1/namespaces/$NAMESPACE/buildconfigs/$NAME/webhooks/$PATH
----

==== Path parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|name|name of the Build
|namespace|object name and auth scope, such as for teams and projects
|path|path to the resource
|===

==== Query parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|path|Path is the URL path to use for the current proxy request to pod.
|===

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|string
|401 Unauthorized|
|===

==== Consumes

* \*/*

==== Produces

* \*/*



