= v1.DeploymentConfigRollback
{product-author}
{product-version}
:data-uri:
:icons:
:toc: macro
:toc-title:
:toclevels: 2

toc::[]

== Description
[%hardbreaks]
DeploymentConfigRollback provides the input to rollback generation.

== Object Schema
Expand or mouse-over a field for more information about it.

++++
<pre>
<div style="margin-left:13px;"><span title="(string) APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources">apiVersion</span>:
</div><div style="margin-left:13px;"><span title="(string) Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds">kind</span>:
</div><div style="margin-left:13px;"><span title="(string) Name of the deployment config that will be rolled back.">name</span>:
</div><details open><summary><span title="(v1.DeploymentConfigRollbackSpec) Spec defines the options to rollback generation.">spec</span>:
</summary><details><summary>  <span title="(v1.ObjectReference) From points to a ReplicationController which is a deployment.">from</span>:
</summary><div style="margin-left:13px;">    <span title="(string) API version of the referent.">apiVersion</span>:
</div><div style="margin-left:13px;">    <span title="(string) If referring to a piece of an object instead of an entire object, this string should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2]. For example, if the object reference is to a container within a pod, this would take on a value like: &#34;spec.containers{name}&#34; (where &#34;name&#34; refers to the name of the container that triggered the event) or if no container name is specified &#34;spec.containers[2]&#34; (container with index 2 in this pod). This syntax is chosen only to have some well-defined way of referencing a part of an object.">fieldPath</span>:
</div><div style="margin-left:13px;">    <span title="(string) Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds">kind</span>:
</div><div style="margin-left:13px;">    <span title="(string) Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names">name</span>:
</div><div style="margin-left:13px;">    <span title="(string) Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/">namespace</span>:
</div><div style="margin-left:13px;">    <span title="(string) Specific resourceVersion to which this reference is made, if any. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#concurrency-control-and-consistency">resourceVersion</span>:
</div><div style="margin-left:13px;">    <span title="(string) UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids">uid</span>:
</div></details><div style="margin-left:13px;">  <span title="(boolean) IncludeReplicationMeta specifies whether to include the replica count and selector.">includeReplicationMeta</span>:
</div><div style="margin-left:13px;">  <span title="(boolean) IncludeStrategy specifies whether to include the deployment Strategy.">includeStrategy</span>:
</div><div style="margin-left:13px;">  <span title="(boolean) IncludeTemplate specifies whether to include the PodTemplateSpec.">includeTemplate</span>:
</div><div style="margin-left:13px;">  <span title="(boolean) IncludeTriggers specifies whether to include config Triggers.">includeTriggers</span>:
</div><div style="margin-left:13px;">  <span title="(integer) Revision to rollback to. If set to 0, rollback to the last revision.">revision</span>:
</div></details><details><summary><span title="(object) UpdatedAnnotations is a set of new annotations that will be added in the deployment config.">updatedAnnotations</span>:
</summary><div style="margin-left:13px;">  <span title="(string)">[string]</span>:
</div></details>
</pre>
++++

== Operations

[[Post-oapi-v1-deploymentconfigrollbacks]]
=== Create a DeploymentConfigRollback
Create a DeploymentConfigRollback

==== HTTP request
----
POST /oapi/v1/deploymentconfigrollbacks HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
Content-Type: application/json'

{
  "kind": "DeploymentConfigRollback",
  "apiVersion": "v1",
  ...
}

----

==== Curl request
----
$ curl -k \
    -X POST \
    -d @- \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
    https://$ENDPOINT/oapi/v1/deploymentconfigrollbacks <<'EOF'
{
  "kind": "DeploymentConfigRollback",
  "apiVersion": "v1",
  ...
}
EOF
----

==== HTTP body
[cols="1,5", options="header"]
|===
|Parameter|Schema
|body|v1.DeploymentConfigRollback
|===

==== Query parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|pretty|If 'true', then the output is pretty printed.
|===

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.DeploymentConfigRollback
|401 Unauthorized|
|===

==== Consumes

* \*/*

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf


[[Post-oapi-v1-namespaces-namespace-deploymentconfigrollbacks]]
=== Create a DeploymentConfigRollback in a namespace
Create a DeploymentConfigRollback

==== HTTP request
----
POST /oapi/v1/namespaces/$NAMESPACE/deploymentconfigrollbacks HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
Content-Type: application/json'

{
  "kind": "DeploymentConfigRollback",
  "apiVersion": "v1",
  ...
}

----

==== Curl request
----
$ curl -k \
    -X POST \
    -d @- \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
    https://$ENDPOINT/oapi/v1/namespaces/$NAMESPACE/deploymentconfigrollbacks <<'EOF'
{
  "kind": "DeploymentConfigRollback",
  "apiVersion": "v1",
  ...
}
EOF
----

==== HTTP body
[cols="1,5", options="header"]
|===
|Parameter|Schema
|body|v1.DeploymentConfigRollback
|===

==== Path parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|namespace|object name and auth scope, such as for teams and projects
|===

==== Query parameters
[cols="1,5", options="header"]
|===
|Parameter|Description
|pretty|If 'true', then the output is pretty printed.
|===

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.DeploymentConfigRollback
|401 Unauthorized|
|===

==== Consumes

* \*/*

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf



