#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

OS_ROOT=$(dirname "${BASH_SOURCE}")/..
source "${OS_ROOT}/hack/common.sh"

cd "${OS_ROOT}"

SPECROOT="${OS_ROOT}/api/swagger-spec"
TMP_SPECROOT="${OS_ROOT}/_tmp/swagger-spec"

mkdir -p "${TMP_SPECROOT}"

echo "generating fresh swagger spec..."
${OS_ROOT}/hack/update-swagger-spec.sh ${TMP_SPECROOT}
echo "diffing ${SPECROOT} against freshly generated swagger spec"
ret=0
diff -Naupr -I 'Auto generated by' "${SPECROOT}" "${TMP_SPECROOT}" || ret=$?
rm -rf "${TMP_SPECROOT}"
if [[ $ret -eq 0 ]]
then
  echo -e "${SPECROOT} up to date."
else
  echo -e "${SPECROOT} is out of date. Please run hack/update-swagger-spec.sh"
  exit 1
fi