// +build !ignore_autogenerated_openshift

// This file was autogenerated by defaulter-gen. Do not edit it manually!

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&Route{}, func(obj interface{}) { SetObjectDefaults_Route(obj.(*Route)) })
	scheme.AddTypeDefaultingFunc(&RouteList{}, func(obj interface{}) { SetObjectDefaults_RouteList(obj.(*RouteList)) })
	return nil
}

func SetObjectDefaults_Route(in *Route) {
	SetDefaults_RouteSpec(&in.Spec)
	SetDefaults_RouteTargetReference(&in.Spec.To)
	for i := range in.Spec.AlternateBackends {
		a := &in.Spec.AlternateBackends[i]
		SetDefaults_RouteTargetReference(a)
	}
	if in.Spec.TLS != nil {
		SetDefaults_TLSConfig(in.Spec.TLS)
	}
	for i := range in.Status.Ingress {
		a := &in.Status.Ingress[i]
		SetDefaults_RouteIngress(a)
	}
}

func SetObjectDefaults_RouteList(in *RouteList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_Route(a)
	}
}
