/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package internalversion

import (
	servicecatalog "github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ServiceInstanceCredentialLister helps list ServiceInstanceCredentials.
type ServiceInstanceCredentialLister interface {
	// List lists all ServiceInstanceCredentials in the indexer.
	List(selector labels.Selector) (ret []*servicecatalog.ServiceInstanceCredential, err error)
	// ServiceInstanceCredentials returns an object that can list and get ServiceInstanceCredentials.
	ServiceInstanceCredentials(namespace string) ServiceInstanceCredentialNamespaceLister
	ServiceInstanceCredentialListerExpansion
}

// serviceInstanceCredentialLister implements the ServiceInstanceCredentialLister interface.
type serviceInstanceCredentialLister struct {
	indexer cache.Indexer
}

// NewServiceInstanceCredentialLister returns a new ServiceInstanceCredentialLister.
func NewServiceInstanceCredentialLister(indexer cache.Indexer) ServiceInstanceCredentialLister {
	return &serviceInstanceCredentialLister{indexer: indexer}
}

// List lists all ServiceInstanceCredentials in the indexer.
func (s *serviceInstanceCredentialLister) List(selector labels.Selector) (ret []*servicecatalog.ServiceInstanceCredential, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*servicecatalog.ServiceInstanceCredential))
	})
	return ret, err
}

// ServiceInstanceCredentials returns an object that can list and get ServiceInstanceCredentials.
func (s *serviceInstanceCredentialLister) ServiceInstanceCredentials(namespace string) ServiceInstanceCredentialNamespaceLister {
	return serviceInstanceCredentialNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ServiceInstanceCredentialNamespaceLister helps list and get ServiceInstanceCredentials.
type ServiceInstanceCredentialNamespaceLister interface {
	// List lists all ServiceInstanceCredentials in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*servicecatalog.ServiceInstanceCredential, err error)
	// Get retrieves the ServiceInstanceCredential from the indexer for a given namespace and name.
	Get(name string) (*servicecatalog.ServiceInstanceCredential, error)
	ServiceInstanceCredentialNamespaceListerExpansion
}

// serviceInstanceCredentialNamespaceLister implements the ServiceInstanceCredentialNamespaceLister
// interface.
type serviceInstanceCredentialNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ServiceInstanceCredentials in the indexer for a given namespace.
func (s serviceInstanceCredentialNamespaceLister) List(selector labels.Selector) (ret []*servicecatalog.ServiceInstanceCredential, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*servicecatalog.ServiceInstanceCredential))
	})
	return ret, err
}

// Get retrieves the ServiceInstanceCredential from the indexer for a given namespace and name.
func (s serviceInstanceCredentialNamespaceLister) Get(name string) (*servicecatalog.ServiceInstanceCredential, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(servicecatalog.Resource("serviceinstancecredential"), name)
	}
	return obj.(*servicecatalog.ServiceInstanceCredential), nil
}
