FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.24-openshift-4.20 AS builder
WORKDIR /go/src/github.com/openshift/origin
COPY . .
RUN make; \
    mkdir -p /tmp/build; \
    cp /go/src/github.com/openshift/origin/openshift-tests /tmp/build/openshift-tests

FROM registry.ci.openshift.org/ocp/4.20:tools
COPY --from=builder /tmp/build/openshift-tests /usr/bin/
RUN mkdir -p /manifests
COPY --from=builder /go/src/github.com/openshift/origin/zz_generated.manifests/* /manifests

RUN PACKAGES="git gzip util-linux" && \
    if [ $HOSTTYPE = x86_64 ]; then PACKAGES="$PACKAGES python3-cinderclient"; fi && \
    if [ $HOSTTYPE = x86_64 ]; then PACKAGES="$PACKAGES realtime-tests rteval"; fi && \
    yum install --setopt=tsflags=nodocs -y $PACKAGES && \
    yum update -y python3-six && \
    yum clean all && rm -rf /var/cache/yum/* && \
    git config --system user.name test && \
    git config --system user.email test@test.com && \
    chmod g+w /etc/passwd
LABEL io.k8s.display-name="OpenShift End-to-End Tests" \
    io.openshift.release.operator=true \
    io.k8s.description="OpenShift is a platform for developing, building, and deploying containerized applications." \
    io.openshift.build.versions="kubernetes-tests=1.32.5" \
    io.openshift.tags="openshift,tests,e2e"
