name: origin
summary: Enterprise Kubernetes for Developers.
description:| OKD is the Origin community distribution of Kubernetes optimized for continuous application development and multi-tenant deployment.
  
adopt-info: origin

grade: stable
confinement: classic

architectures:
  - build-on: i386
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

apps:
  origin:
    command: bin/origin
    plugs:
      - home
      - network
      - removable-media

parts:
  origin:
  plugin: nil 
    source: https://github.com/openshift/origin.git
    source-type: git
    override-pull: |
      git clone https://github.com/openshift/origin.git src/github.com/openshift/origin
       cd src/github.com/openshift/origin
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | sed 's/v//')"
      override-build: |
      export GOPATH=$PWD
      cd src/github.com/openshift/origin
      env CGO_ENABLED=0 GOOS=linux \
      go build --ldflags "-s -w \
        -X 'github.com/openshift/origin/version.GitCommit=$(git rev-list -1 HEAD)' \
        -X 'github.com/openshift/origin/version.Version=$(git describe --tags --abbrev=0)'" \
        -a -installsuffix cgo -o $SNAPCRAFT_PART_INSTALL/bin/origin
    build-snaps:
      - go
    build-packages:
      - git
      - sed
