// +build !ignore_autogenerated_openshift

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package api

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	labels "k8s.io/apimachinery/pkg/labels"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	reflect "reflect"
)

func init() {
	SchemeBuilder.Register(RegisterDeepCopies)
}

// RegisterDeepCopies adds deep-copy functions to the given scheme. Public
// to allow building arbitrary schemes.
func RegisterDeepCopies(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedDeepCopyFuncs(
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_api_ImageCondition, InType: reflect.TypeOf(&ImageCondition{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_api_ImageExecutionPolicyRule, InType: reflect.TypeOf(&ImageExecutionPolicyRule{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_api_ImagePolicyConfig, InType: reflect.TypeOf(&ImagePolicyConfig{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_api_ImageResolutionPolicyRule, InType: reflect.TypeOf(&ImageResolutionPolicyRule{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_api_ValueCondition, InType: reflect.TypeOf(&ValueCondition{})},
	)
}

// DeepCopy_api_ImageCondition is an autogenerated deepcopy function.
func DeepCopy_api_ImageCondition(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*ImageCondition)
		out := out.(*ImageCondition)
		*out = *in
		if in.OnResources != nil {
			in, out := &in.OnResources, &out.OnResources
			*out = make([]schema.GroupResource, len(*in))
			copy(*out, *in)
		}
		if in.MatchRegistries != nil {
			in, out := &in.MatchRegistries, &out.MatchRegistries
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
		if in.MatchDockerImageLabels != nil {
			in, out := &in.MatchDockerImageLabels, &out.MatchDockerImageLabels
			*out = make([]ValueCondition, len(*in))
			copy(*out, *in)
		}
		if in.MatchImageLabels != nil {
			in, out := &in.MatchImageLabels, &out.MatchImageLabels
			*out = make([]v1.LabelSelector, len(*in))
			for i := range *in {
				if newVal, err := c.DeepCopy(&(*in)[i]); err != nil {
					return err
				} else {
					(*out)[i] = *newVal.(*v1.LabelSelector)
				}
			}
		}
		if in.MatchImageLabelSelectors != nil {
			in, out := &in.MatchImageLabelSelectors, &out.MatchImageLabelSelectors
			*out = make([]labels.Selector, len(*in))
			for i := range *in {
				if newVal, err := c.DeepCopy(&(*in)[i]); err != nil {
					return err
				} else {
					(*out)[i] = *newVal.(*labels.Selector)
				}
			}
		}
		if in.MatchImageAnnotations != nil {
			in, out := &in.MatchImageAnnotations, &out.MatchImageAnnotations
			*out = make([]ValueCondition, len(*in))
			copy(*out, *in)
		}
		return nil
	}
}

// DeepCopy_api_ImageExecutionPolicyRule is an autogenerated deepcopy function.
func DeepCopy_api_ImageExecutionPolicyRule(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*ImageExecutionPolicyRule)
		out := out.(*ImageExecutionPolicyRule)
		*out = *in
		if err := DeepCopy_api_ImageCondition(&in.ImageCondition, &out.ImageCondition, c); err != nil {
			return err
		}
		return nil
	}
}

// DeepCopy_api_ImagePolicyConfig is an autogenerated deepcopy function.
func DeepCopy_api_ImagePolicyConfig(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*ImagePolicyConfig)
		out := out.(*ImagePolicyConfig)
		*out = *in
		if in.ResolutionRules != nil {
			in, out := &in.ResolutionRules, &out.ResolutionRules
			*out = make([]ImageResolutionPolicyRule, len(*in))
			copy(*out, *in)
		}
		if in.ExecutionRules != nil {
			in, out := &in.ExecutionRules, &out.ExecutionRules
			*out = make([]ImageExecutionPolicyRule, len(*in))
			for i := range *in {
				if err := DeepCopy_api_ImageExecutionPolicyRule(&(*in)[i], &(*out)[i], c); err != nil {
					return err
				}
			}
		}
		return nil
	}
}

// DeepCopy_api_ImageResolutionPolicyRule is an autogenerated deepcopy function.
func DeepCopy_api_ImageResolutionPolicyRule(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*ImageResolutionPolicyRule)
		out := out.(*ImageResolutionPolicyRule)
		*out = *in
		return nil
	}
}

// DeepCopy_api_ValueCondition is an autogenerated deepcopy function.
func DeepCopy_api_ValueCondition(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*ValueCondition)
		out := out.(*ValueCondition)
		*out = *in
		return nil
	}
}
