#!/bin/bash
# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

if [[ "${NO_TTY:-}" -eq 1 ]]; then
  TTY_ARGS=''
else
  TTY_ARGS='-it'
fi

# If our version of these dirs don't exist then create them.
# This will allow us to not mess with the user's own version of these
# files for other k8s related activities.
mkdir -p ${ROOT}/.var/run/kubernetes-service-catalog ${ROOT}/.kube ${ROOT}/.run

# Run kubectl in a container - make sure we cd into the correct dir
# based on the current working dir. Yes, this assumes that you're running
# this script from within our git repo source tree

docker run ${TTY_ARGS} --rm --net host \
	-w /root/service-catalog${PWD#${ROOT}} \
	-v ${ROOT}/.var/run/kubernetes-service-catalog:/var/run/kubernetes-service-catalog \
	-v ${ROOT}/.kube:/.kube \
	-v ${ROOT}:/root/service-catalog \
	--privileged \
	kubectl ${SERVER_INFO} $*
