.TH "OC ADM" "1" " Openshift CLI User Manuals" "Openshift" "June 2016"  ""


.SH NAME
.PP
oc adm create\-api\-client\-config \- Create a config file for connecting to the server as a user


.SH SYNOPSIS
.PP
\fBoc adm create\-api\-client\-config\fP [OPTIONS]


.SH DESCRIPTION
.PP
Create a client configuration for connecting to the server

.PP
This command creates a folder containing a client certificate, a client key, a server certificate authority, and a .kubeconfig file for connecting to the master as the provided user.


.SH OPTIONS
.PP
\fB\-\-basename\fP=""
    The base filename to use for the .crt, .key, and .kubeconfig files. Defaults to the username.

.PP
\fB\-\-certificate\-authority\fP=[openshift.local.config/master/ca.crt]
    Files containing signing authorities to use to verify the API server's serving certificate.

.PP
\fB\-\-client\-dir\fP=""
    The client data directory.

.PP
\fB\-\-groups\fP=[]
    The list of groups this user belongs to. Comma delimited list

.PP
\fB\-\-master\fP="
\[la]https://localhost:8443"\[ra]
    The API server's URL.

.PP
\fB\-\-public\-master\fP=""
    The API public facing server's URL (if applicable).

.PP
\fB\-\-signer\-cert\fP="openshift.local.config/master/ca.crt"
    The certificate file.

.PP
\fB\-\-signer\-key\fP="openshift.local.config/master/ca.key"
    The key file.

.PP
\fB\-\-signer\-serial\fP="openshift.local.config/master/ca.serial.txt"
    The serial file that keeps track of how many certs have been signed.

.PP
\fB\-\-user\fP=""
    The scope qualified username.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-api\-version\fP=""
    DEPRECATED: The API version to use when talking to the server

.PP
\fB\-\-as\fP=""
    Username to impersonate for the operation

.PP
\fB\-\-client\-certificate\fP=""
    Path to a client certificate file for TLS

.PP
\fB\-\-client\-key\fP=""
    Path to a client key file for TLS

.PP
\fB\-\-cluster\fP=""
    The name of the kubeconfig cluster to use

.PP
\fB\-\-config\fP=""
    Path to the config file to use for CLI requests.

.PP
\fB\-\-context\fP=""
    The name of the kubeconfig context to use

.PP
\fB\-\-google\-json\-key\fP=""
    The Google Cloud Platform Service Account JSON Key to use for authentication.

.PP
\fB\-\-insecure\-skip\-tls\-verify\fP=false
    If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure

.PP
\fB\-\-log\-flush\-frequency\fP=0
    Maximum number of seconds between log flushes

.PP
\fB\-\-match\-server\-version\fP=false
    Require server version to match client version

.PP
\fB\-n\fP, \fB\-\-namespace\fP=""
    If present, the namespace scope for this CLI request

.PP
\fB\-\-request\-timeout\fP="0"
    The length of time to wait before giving up on a single server request. Non\-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests.

.PP
\fB\-\-server\fP=""
    The address and port of the Kubernetes API server

.PP
\fB\-\-token\fP=""
    Bearer token for authentication to the API server


.SH SEE ALSO
.PP
\fBoc\-adm(1)\fP,


.SH HISTORY
.PP
June 2016, Ported from the Kubernetes man\-doc generator
