.TH "OC" "1" " Openshift CLI User Manuals" "Openshift" "June 2016"  ""


.SH NAME
.PP
oc cluster \- Start and stop OpenShift cluster


.SH SYNOPSIS
.PP
\fBoc cluster\fP [OPTIONS]


.SH DESCRIPTION
.PP
Manage a local OpenShift cluster

.PP
The OpenShift cluster will run as an all\-in\-one container on a Docker host. The Docker host may be a local VM (ie. using docker\-machine on OS X and Windows clients), remote machine, or the local Unix host.

.PP
To use an existing Docker connection, ensure that Docker commands are working and that you can create new containers. For OS X and Windows clients, a docker\-machine with the VirtualBox driver can be created for you using the \-\-create\-machine option.

.PP
By default, etcd data will not be preserved between container restarts. If you wish to preserve your data, specify a value for \-\-host\-data\-dir and the \-\-use\-existing\-config flag.

.PP
Default routes are setup using xip.io and the host ip of your cluster. To use a different routing suffix, use the \-\-routing\-suffix flag.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-api\-version\fP=""
    DEPRECATED: The API version to use when talking to the server

.PP
\fB\-\-as\fP=""
    Username to impersonate for the operation

.PP
\fB\-\-certificate\-authority\fP=""
    Path to a cert. file for the certificate authority

.PP
\fB\-\-client\-certificate\fP=""
    Path to a client certificate file for TLS

.PP
\fB\-\-client\-key\fP=""
    Path to a client key file for TLS

.PP
\fB\-\-cluster\fP=""
    The name of the kubeconfig cluster to use

.PP
\fB\-\-config\fP=""
    Path to the config file to use for CLI requests.

.PP
\fB\-\-context\fP=""
    The name of the kubeconfig context to use

.PP
\fB\-\-google\-json\-key\fP=""
    The Google Cloud Platform Service Account JSON Key to use for authentication.

.PP
\fB\-\-insecure\-skip\-tls\-verify\fP=false
    If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure

.PP
\fB\-\-log\-flush\-frequency\fP=0
    Maximum number of seconds between log flushes

.PP
\fB\-\-match\-server\-version\fP=false
    Require server version to match client version

.PP
\fB\-n\fP, \fB\-\-namespace\fP=""
    If present, the namespace scope for this CLI request

.PP
\fB\-\-request\-timeout\fP="0"
    The length of time to wait before giving up on a single server request. Non\-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests.

.PP
\fB\-\-server\fP=""
    The address and port of the Kubernetes API server

.PP
\fB\-\-token\fP=""
    Bearer token for authentication to the API server

.PP
\fB\-\-user\fP=""
    The name of the kubeconfig user to use


.SH SEE ALSO
.PP
\fBoc(1)\fP, \fBoc\-cluster\-down(1)\fP, \fBoc\-cluster\-status(1)\fP, \fBoc\-cluster\-up(1)\fP,


.SH HISTORY
.PP
June 2016, Ported from the Kubernetes man\-doc generator
