.TH "OC SECRETS" "1" " Openshift CLI User Manuals" "Openshift" "June 2016"  ""


.SH NAME
.PP
oc secrets new\-sshauth \- Create a new secret for SSH authentication


.SH SYNOPSIS
.PP
\fBoc secrets new\-sshauth\fP [OPTIONS]


.SH DESCRIPTION
.PP
Create a new SSH authentication secret

.PP
SSH authentication secrets are used to authenticate against SCM servers.

.PP
When creating applications, you may have a SCM server that requires SSH authentication \- private SSH key. In order for the nodes to clone source code on your behalf, they have to have the credentials. You can provide this information by creating a 'sshauth' secret and attaching it to your service account.


.SH OPTIONS
.PP
\fB\-\-ca\-cert\fP=""
    Path to a certificate file

.PP
\fB\-\-gitconfig\fP=""
    Path to a .gitconfig file

.PP
\fB\-\-no\-headers\fP=false
    When using the default or custom\-column output format, don't print headers.

.PP
\fB\-o\fP, \fB\-\-output\fP=""
    Output format. One of: json|yaml|wide|name|custom\-columns=...|custom\-columns\-file=...|go\-template=...|go\-template\-file=...|jsonpath=...|jsonpath\-file=... See custom columns [
\[la]http://kubernetes.io/docs/user-guide/kubectl-overview/#custom-columns\[ra]], golang template [
\[la]http://golang.org/pkg/text/template/#pkg-overview\[ra]] and jsonpath template [
\[la]http://kubernetes.io/docs/user-guide/jsonpath\[ra]].

.PP
\fB\-\-output\-version\fP=""
    Output the formatted object with the given group version (for ex: 'extensions/v1beta1').

.PP
\fB\-a\fP, \fB\-\-show\-all\fP=true
    When printing, show all resources (false means hide terminated pods.)

.PP
\fB\-\-show\-labels\fP=false
    When printing, show all labels as the last column (default hide labels column)

.PP
\fB\-\-sort\-by\fP=""
    If non\-empty, sort list types using this field specification.  The field specification is expressed as a JSONPath expression (e.g. '{.metadata.name}'). The field in the API resource specified by this JSONPath expression must be an integer or a string.

.PP
\fB\-\-ssh\-privatekey\fP=""
    Path to a SSH private key file

.PP
\fB\-\-template\fP=""
    Template string or path to template file to use when \-o=go\-template, \-o=go\-template\-file. The template format is golang templates [
\[la]http://golang.org/pkg/text/template/#pkg-overview\[ra]].


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-api\-version\fP=""
    DEPRECATED: The API version to use when talking to the server

.PP
\fB\-\-as\fP=""
    Username to impersonate for the operation

.PP
\fB\-\-certificate\-authority\fP=""
    Path to a cert. file for the certificate authority

.PP
\fB\-\-client\-certificate\fP=""
    Path to a client certificate file for TLS

.PP
\fB\-\-client\-key\fP=""
    Path to a client key file for TLS

.PP
\fB\-\-cluster\fP=""
    The name of the kubeconfig cluster to use

.PP
\fB\-\-config\fP=""
    Path to the config file to use for CLI requests.

.PP
\fB\-\-context\fP=""
    The name of the kubeconfig context to use

.PP
\fB\-\-google\-json\-key\fP=""
    The Google Cloud Platform Service Account JSON Key to use for authentication.

.PP
\fB\-\-insecure\-skip\-tls\-verify\fP=false
    If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure

.PP
\fB\-\-log\-flush\-frequency\fP=0
    Maximum number of seconds between log flushes

.PP
\fB\-\-match\-server\-version\fP=false
    Require server version to match client version

.PP
\fB\-n\fP, \fB\-\-namespace\fP=""
    If present, the namespace scope for this CLI request

.PP
\fB\-\-request\-timeout\fP="0"
    The length of time to wait before giving up on a single server request. Non\-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests.

.PP
\fB\-\-server\fP=""
    The address and port of the Kubernetes API server

.PP
\fB\-\-token\fP=""
    Bearer token for authentication to the API server

.PP
\fB\-\-user\fP=""
    The name of the kubeconfig user to use


.SH EXAMPLE
.PP
.RS

.nf
  # If your SSH authentication method requires only private SSH key, add it by using:
  oc secrets new\-sshauth SECRET \-\-ssh\-privatekey=FILENAME
  
  # If your SSH authentication method requires also CA certificate, add it by using:
  oc secrets new\-sshauth SECRET \-\-ssh\-privatekey=FILENAME \-\-ca\-cert=FILENAME
  
  # If you do already have a .gitconfig file needed for authentication, you can create a gitconfig secret by using:
  oc secrets new SECRET path/to/.gitconfig

.fi
.RE


.SH SEE ALSO
.PP
\fBoc\-secrets(1)\fP,


.SH HISTORY
.PP
June 2016, Ported from the Kubernetes man\-doc generator
