.TH "OPENSHIFT START KUBERNETES" "1" " Openshift CLI User Manuals" "Openshift" "June 2016"  ""


.SH NAME
.PP
openshift start kubernetes kubelet \- Launch the Kubelet (kubelet)


.SH SYNOPSIS
.PP
\fBopenshift start kubernetes kubelet\fP [OPTIONS]


.SH DESCRIPTION
.PP
Start Kubelet

.PP
This command launches a Kubelet. All options are exposed. Use 'openshift start node' for
starting from a configuration file.


.SH OPTIONS
.PP
\fB\-\-address\fP=0.0.0.0
    The IP address for the Kubelet to serve on (set to 0.0.0.0 for all interfaces)

.PP
\fB\-\-allow\-privileged\fP=false
    If true, allow containers to request privileged mode. [default=false]

.PP
\fB\-\-alsologtostderr\fP=false
    log to standard error as well as files

.PP
\fB\-\-api\-servers\fP=[]
    List of Kubernetes API servers for publishing events, and reading pods and services. (ip:port), comma separated.

.PP
\fB\-\-application\-metrics\-count\-limit\fP=100
    Max number of application metrics to store (per container)

.PP
\fB\-\-auth\-path\fP="/var/lib/kubelet/kubernetes\_auth"
    Path to .kubernetes\_auth file, specifying how to authenticate to API server.

.PP
\fB\-\-babysit\-daemons\fP=false
    If true, the node has babysitter process monitoring docker and kubelet.

.PP
\fB\-\-boot\-id\-file\fP="/proc/sys/kernel/random/boot\_id"
    Comma\-separated list of files to check for boot\-id. Use the first one that exists.

.PP
\fB\-\-cadvisor\-port\fP=4194
    The port of the localhost cAdvisor endpoint

.PP
\fB\-\-cert\-dir\fP="/var/run/kubernetes"
    The directory where the TLS certs are located (by default /var/run/kubernetes). If \-\-tls\-cert\-file and \-\-tls\-private\-key\-file are provided, this flag will be ignored.

.PP
\fB\-\-cgroup\-root\fP=""
    Optional root cgroup to use for pods. This is handled by the container runtime on a best effort basis. Default: '', which means use the container runtime default.

.PP
\fB\-\-chaos\-chance\fP=0
    If > 0.0, introduce random client errors and latency. Intended for testing. [default=0.0]

.PP
\fB\-\-cloud\-config\fP=""
    The path to the cloud provider configuration file.  Empty string for no configuration file.

.PP
\fB\-\-cloud\-provider\fP=""
    The provider for cloud services.  Empty string for no provider.

.PP
\fB\-\-cluster\-dns\fP=""
    IP address for a cluster DNS server.  This value is used for containers' DNS server in case of Pods with "dnsPolicy=ClusterFirst"

.PP
\fB\-\-cluster\-domain\fP=""
    Domain for this cluster.  If set, kubelet will configure all containers to search this domain in addition to the host's search domains

.PP
\fB\-\-config\fP=""
    Path to the config file or directory of files

.PP
\fB\-\-configure\-cbr0\fP=false
    If true, kubelet will configure cbr0 based on Node.Spec.PodCIDR.

.PP
\fB\-\-container\-hints\fP="/etc/cadvisor/container\_hints.json"
    location of the container hints file

.PP
\fB\-\-container\-runtime\fP="docker"
    The container runtime to use. Possible values: 'docker', 'rkt'. Default: 'docker'.

.PP
\fB\-\-containerized\fP=false
    Experimental support for running kubelet in a container.  Intended for testing. [default=false]

.PP
\fB\-\-cpu\-cfs\-quota\fP=true
    Enable CPU CFS quota enforcement for containers that specify CPU limits

.PP
\fB\-\-docker\fP="unix:///var/run/docker.sock"
    docker endpoint

.PP
\fB\-\-docker\-endpoint\fP=""
    If non\-empty, use this for the docker endpoint to communicate with

.PP
\fB\-\-docker\-env\-metadata\-whitelist\fP=""
    a comma\-separated list of environment variable keys that needs to be collected for docker containers

.PP
\fB\-\-docker\-exec\-handler\fP="native"
    Handler to use when executing a command in a container. Valid values are 'native' and 'nsenter'. Defaults to 'native'.

.PP
\fB\-\-docker\-only\fP=false
    Only report docker containers in addition to root stats

.PP
\fB\-\-docker\-root\fP="/var/lib/docker"
    Absolute path to the Docker state root directory (default: /var/lib/docker)

.PP
\fB\-\-docker\-run\fP="/var/run/docker"
    Absolute path to the Docker run directory (default: /var/run/docker)

.PP
\fB\-\-enable\-custom\-metrics\fP=false
    Support for gathering custom metrics.

.PP
\fB\-\-enable\-debugging\-handlers\fP=true
    Enables server endpoints for log collection and local running of containers and commands

.PP
\fB\-\-enable\-load\-reader\fP=false
    Whether to enable cpu load reader

.PP
\fB\-\-enable\-server\fP=true
    Enable the Kubelet's server

.PP
\fB\-\-event\-burst\fP=10
    Maximum size of a bursty event records, temporarily allows event records to burst to this number, while still not exceeding event\-qps. Only used if \-\-event\-qps > 0

.PP
\fB\-\-event\-qps\fP=5
    If > 0, limit event creations per second to this value. If 0, unlimited.

.PP
\fB\-\-event\-storage\-age\-limit\fP="default=24h"
    Max length of time for which to store events (per type). Value is a comma separated list of key values, where the keys are event types (e.g.: creation, oom) or "default" and the value is a duration. Default is applied to all non\-specified event types

.PP
\fB\-\-event\-storage\-event\-limit\fP="default=100000"
    Max number of events to store (per type). Value is a comma separated list of key values, where the keys are event types (e.g.: creation, oom) or "default" and the value is an integer. Default is applied to all non\-specified event types

.PP
\fB\-\-eviction\-hard\fP=""
    A set of eviction thresholds (e.g. memory.available<1Gi) that if met would trigger a pod eviction.

.PP
\fB\-\-eviction\-soft\fP=""
    A set of eviction thresholds (e.g. memory.available<1.5Gi) that if met over a corresponding grace period would trigger a pod eviction.

.PP
\fB\-\-eviction\-soft\-grace\-period\fP=""
    A set of eviction grace periods (e.g. memory.available=1m30s) that correspond to how long a soft eviction threshold must hold before triggering a pod eviction.

.PP
\fB\-\-experimental\-flannel\-overlay\fP=false
    Experimental support for starting the kubelet with the default overlay network (flannel). Assumes flanneld is already running in client mode. [default=false]

.PP
\fB\-\-file\-check\-frequency\fP=0
    Duration between checking config files for new data

.PP
\fB\-\-global\-housekeeping\-interval\fP=0
    Interval between global housekeepings

.PP
\fB\-\-hairpin\-mode\fP="promiscuous\-bridge"
    How should the kubelet setup hairpin NAT. This allows endpoints of a Service to loadbalance back to themselves if they should try to access their own Service. Valid values are "promiscuous\-bridge", "hairpin\-veth" and "none".

.PP
\fB\-\-healthz\-bind\-address\fP=127.0.0.1
    The IP address for the healthz server to serve on, defaulting to 127.0.0.1 (set to 0.0.0.0 for all interfaces)

.PP
\fB\-\-healthz\-port\fP=10248
    The port of the localhost healthz endpoint

.PP
\fB\-\-host\-ipc\-sources\fP="\fI"
    Comma\-separated list of sources from which the Kubelet allows pods to use the host ipc namespace. [default="\fP"]

.PP
\fB\-\-host\-network\-sources\fP="\fI"
    Comma\-separated list of sources from which the Kubelet allows pods to use of host network. [default="\fP"]

.PP
\fB\-\-host\-pid\-sources\fP="\fI"
    Comma\-separated list of sources from which the Kubelet allows pods to use the host pid namespace. [default="\fP"]

.PP
\fB\-\-hostname\-override\fP=""
    If non\-empty, will use this string as identification instead of the actual hostname.

.PP
\fB\-\-housekeeping\-interval\fP=0
    Interval between container housekeepings

.PP
\fB\-\-http\-check\-frequency\fP=0
    Duration between checking http for new data

.PP
\fB\-\-httptest.serve\fP=""
    if non\-empty, httptest.NewServer serves on this address and blocks

.PP
\fB\-\-image\-gc\-high\-threshold\fP=90
    The percent of disk usage after which image garbage collection is always run. Default: 90%

.PP
\fB\-\-image\-gc\-low\-threshold\fP=80
    The percent of disk usage before which image garbage collection is never run. Lowest disk usage to garbage collect to. Default: 80%

.PP
\fB\-\-ir\-data\-source\fP="influxdb"
    Data source used by InitialResources. Supported options: influxdb, gcm.

.PP
\fB\-\-ir\-dbname\fP="k8s"
    InfluxDB database name which contains metrics requred by InitialResources

.PP
\fB\-\-ir\-hawkular\fP=""
    Hawkular configuration URL

.PP
\fB\-\-ir\-influxdb\-host\fP="localhost:8080/api/v1/proxy/namespaces/kube\-system/services/monitoring\-influxdb:api"
    Address of InfluxDB which contains metrics requred by InitialResources

.PP
\fB\-\-ir\-namespace\-only\fP=false
    Whether the estimation should be made only based on data from the same namespace.

.PP
\fB\-\-ir\-password\fP="root"
    Password used for connecting to InfluxDB

.PP
\fB\-\-ir\-percentile\fP=90
    Which percentile of samples should InitialResources use when estimating resources. For experiment purposes.

.PP
\fB\-\-ir\-user\fP="root"
    User used for connecting to InfluxDB

.PP
\fB\-\-kube\-api\-burst\fP=10
    Burst to use while talking with kubernetes apiserver

.PP
\fB\-\-kube\-api\-content\-type\fP=""
    ContentType of requests sent to apiserver. Passing application/vnd.kubernetes.protobuf is an experimental feature now.

.PP
\fB\-\-kube\-api\-qps\fP=5
    QPS to use while talking with kubernetes apiserver

.PP
\fB\-\-kube\-reserved\fP=
    A set of ResourceName=ResourceQuantity (e.g. cpu=200m,memory=150G) pairs that describe resources reserved for kubernetes system components. Currently only cpu and memory are supported. See 
\[la]http://releases.k8s.io/HEAD/docs/user-guide/compute-resources.md\[ra] for more detail. [default=none]

.PP
\fB\-\-kubeconfig\fP="/var/lib/kubelet/kubeconfig"
    Path to a kubeconfig file, specifying how to authenticate to API server (the master location is set by the api\-servers flag).

.PP
\fB\-\-kubelet\-cgroups\fP=""
    Optional absolute name of cgroups to create and run the Kubelet in.

.PP
\fB\-\-lock\-file\fP=""
    <Warning: Alpha feature> The path to file for kubelet to use as a lock file.

.PP
\fB\-\-log\-backtrace\-at\fP=:0
    when logging hits line file:N, emit a stack trace

.PP
\fB\-\-log\-cadvisor\-usage\fP=false
    Whether to log the usage of the cAdvisor container

.PP
\fB\-\-log\-dir\fP=""
    If non\-empty, write log files in this directory

.PP
\fB\-\-logtostderr\fP=true
    log to standard error instead of files

.PP
\fB\-\-low\-diskspace\-threshold\-mb\fP=256
    The absolute free disk space, in MB, to maintain. When disk space falls below this threshold, new pods would be rejected. Default: 256

.PP
\fB\-\-machine\-id\-file\fP="/etc/machine\-id,/var/lib/dbus/machine\-id"
    Comma\-separated list of files to check for machine\-id. Use the first one that exists.

.PP
\fB\-\-manifest\-url\fP=""
    URL for accessing the container manifest

.PP
\fB\-\-manifest\-url\-header\fP=""
    HTTP header to use when accessing the manifest URL, with the key separated from the value with a ':', as in 'key:value'

.PP
\fB\-\-master\-service\-namespace\fP="default"
    The namespace from which the kubernetes master services should be injected into pods

.PP
\fB\-\-max\-open\-files\fP=1000000
    Number of files that can be opened by Kubelet process. [default=1000000]

.PP
\fB\-\-max\-pods\fP=110
    Number of Pods that can run on this Kubelet.

.PP
\fB\-\-maximum\-dead\-containers\fP=240
    Maximum number of old instances of containers to retain globally.  Each container takes up some disk space.  Default: 100.

.PP
\fB\-\-maximum\-dead\-containers\-per\-container\fP=2
    Maximum number of old instances to retain per container.  Each container takes up some disk space.  Default: 2.

.PP
\fB\-\-minimum\-container\-ttl\-duration\fP=0
    Minimum age for a finished container before it is garbage collected.  Examples: '300ms', '10s' or '2h45m'

.PP
\fB\-\-minimum\-image\-ttl\-duration\fP=0
    Minimum age for a unused image before it is garbage collected.  Examples: '300ms', '10s' or '2h45m'. Default: '2m'

.PP
\fB\-\-network\-plugin\fP=""
    <Warning: Alpha feature> The name of the network plugin to be invoked for various events in kubelet/pod lifecycle

.PP
\fB\-\-network\-plugin\-dir\fP="/usr/libexec/kubernetes/kubelet\-plugins/net/exec/"
    <Warning: Alpha feature> The full path of the directory in which to search for network plugins

.PP
\fB\-\-node\-ip\fP=""
    IP address of the node. If set, kubelet will use this IP address for the node

.PP
\fB\-\-node\-labels\fP=
    <Warning: Alpha feature> Labels to add when registering the node in the cluster.  Labels must be key=value pairs separated by ','.

.PP
\fB\-\-node\-status\-update\-frequency\fP=0
    Specifies how often kubelet posts node status to master. Note: be cautious when changing the constant, it must work with nodeMonitorGracePeriod in nodecontroller. Default: 10s

.PP
\fB\-\-non\-masquerade\-cidr\fP="10.0.0.0/8"
    Traffic to IPs outside this range will use IP masquerade.

.PP
\fB\-\-oom\-score\-adj\fP=\-999
    The oom\-score\-adj value for kubelet process. Values must be within the range [\-1000, 1000]

.PP
\fB\-\-outofdisk\-transition\-frequency\fP=0
    Duration for which the kubelet has to wait before transitioning out of out\-of\-disk node condition status. Default: 5m0s

.PP
\fB\-\-pod\-cidr\fP=""
    The CIDR to use for pod IP addresses, only used in standalone mode.  In cluster mode, this is obtained from the master.

.PP
\fB\-\-pod\-infra\-container\-image\fP="gcr.io/google\_containers/pause\-amd64:3.0"
    The image whose network/ipc namespaces containers in each pod will use.

.PP
\fB\-\-port\fP=10250
    The port for the Kubelet to serve on.

.PP
\fB\-\-read\-only\-port\fP=10255
    The read\-only port for the Kubelet to serve on with no authentication/authorization (set to 0 to disable)

.PP
\fB\-\-really\-crash\-for\-testing\fP=false
    If true, when panics occur crash. Intended for testing.

.PP
\fB\-\-reconcile\-cidr\fP=true
    Reconcile node CIDR with the CIDR specified by the API server. No\-op if register\-node or configure\-cbr0 is false. [default=true]

.PP
\fB\-\-register\-node\fP=true
    Register the node with the apiserver (defaults to true if \-\-api\-servers is set)

.PP
\fB\-\-register\-schedulable\fP=true
    Register the node as schedulable. No\-op if register\-node is false. [default=true]

.PP
\fB\-\-registry\-burst\fP=10
    Maximum size of a bursty pulls, temporarily allows pulls to burst to this number, while still not exceeding registry\-qps.  Only used if \-\-registry\-qps > 0

.PP
\fB\-\-registry\-qps\fP=5
    If > 0, limit registry pull QPS to this value.  If 0, unlimited. [default=5.0]

.PP
\fB\-\-resolv\-conf\fP="/etc/resolv.conf"
    Resolver configuration file used as the basis for the container DNS resolution configuration.

.PP
\fB\-\-resource\-container\fP=""
    Optional absolute name of the resource\-only container to create and run the Kubelet in.

.PP
\fB\-\-rkt\-api\-endpoint\fP="localhost:15441"
    The endpoint of the rkt API service to communicate with. Only used if \-\-container\-runtime='rkt'.

.PP
\fB\-\-rkt\-path\fP=""
    Path of rkt binary. Leave empty to use the first rkt in $PATH.  Only used if \-\-container\-runtime='rkt'.

.PP
\fB\-\-rkt\-stage1\-image\fP=""
    image to use as stage1. Local paths and http/https URLs are supported. If empty, the 'stage1.aci' in the same directory as '\-\-rkt\-path' will be used.

.PP
\fB\-\-root\-dir\fP="/var/lib/kubelet"
    Directory path for managing kubelet files (volume mounts,etc).

.PP
\fB\-\-runonce\fP=false
    If true, exit after spawning pods from local manifests or remote urls. Exclusive with \-\-api\-servers, and \-\-enable\-server

.PP
\fB\-\-runtime\-cgroups\fP=""
    Optional absolute name of cgroups to create and run the runtime in.

.PP
\fB\-\-serialize\-image\-pulls\fP=true
    Pull images one at a time. We recommend \fInot\fP changing the default value on nodes that run docker daemon with version < 1.9 or an Aufs storage backend. Issue #10959 has more details. [default=true]

.PP
\fB\-\-stderrthreshold\fP=2
    logs at or above this threshold go to stderr

.PP
\fB\-\-storage\-driver\-buffer\-duration\fP=0
    Writes in the storage driver will be buffered for this duration, and committed to the non memory backends as a single transaction

.PP
\fB\-\-storage\-driver\-db\fP="cadvisor"
    database name

.PP
\fB\-\-storage\-driver\-host\fP="localhost:8086"
    database host:port

.PP
\fB\-\-storage\-driver\-password\fP="root"
    database password

.PP
\fB\-\-storage\-driver\-secure\fP=false
    use secure connection with database

.PP
\fB\-\-storage\-driver\-table\fP="stats"
    table name

.PP
\fB\-\-storage\-driver\-user\fP="root"
    database username

.PP
\fB\-\-streaming\-connection\-idle\-timeout\fP=0
    Maximum time a streaming connection can be idle before the connection is automatically closed. 0 indicates no timeout. Example: '5m'

.PP
\fB\-\-sync\-frequency\fP=0
    Max period between synchronizing running containers and config

.PP
\fB\-\-system\-cgroups\fP=""
    Optional absolute name of cgroups in which to place all non\-kernel processes that are not already inside a cgroup under \fB\fC/\fR. Empty for no container. Rolling back the flag requires a reboot. (Default: "").

.PP
\fB\-\-system\-container\fP=""
    Optional resource\-only container in which to place all non\-kernel processes that are not already in a container. Empty for no container. Rolling back the flag requires a reboot. (Default: "").

.PP
\fB\-\-system\-reserved\fP=
    A set of ResourceName=ResourceQuantity (e.g. cpu=200m,memory=150G) pairs that describe resources reserved for non\-kubernetes components. Currently only cpu and memory are supported. See 
\[la]http://releases.k8s.io/HEAD/docs/user-guide/compute-resources.md\[ra] for more detail. [default=none]

.PP
\fB\-\-tls\-cert\-file\fP=""
    File containing x509 Certificate for HTTPS.  (CA cert, if any, concatenated after server cert). If \-\-tls\-cert\-file and \-\-tls\-private\-key\-file are not provided, a self\-signed certificate and key are generated for the public address and saved to the directory passed to \-\-cert\-dir.

.PP
\fB\-\-tls\-private\-key\-file\fP=""
    File containing x509 private key matching \-\-tls\-cert\-file.

.PP
\fB\-\-v\fP=0
    log level for V logs

.PP
\fB\-\-vmodule\fP=
    comma\-separated list of pattern=N settings for file\-filtered logging

.PP
\fB\-\-volume\-plugin\-dir\fP="/usr/libexec/kubernetes/kubelet\-plugins/volume/exec/"
    <Warning: Alpha feature> The full path of the directory in which to search for additional third party volume plugins

.PP
\fB\-\-volume\-stats\-agg\-period\fP=0
    Specifies interval for kubelet to calculate and cache the volume disk usage for all pods and volumes.  To disable volume calculations, set to 0.  Default: '1m'


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-google\-json\-key\fP=""
    The Google Cloud Platform Service Account JSON Key to use for authentication.

.PP
\fB\-\-log\-flush\-frequency\fP=0
    Maximum number of seconds between log flushes


.SH SEE ALSO
.PP
\fBopenshift\-start\-kubernetes(1)\fP,


.SH HISTORY
.PP
June 2016, Ported from the Kubernetes man\-doc generator
