.TH "OPENSHIFT CLI ADM CONFIG" "1" " Openshift CLI User Manuals" "Openshift" "June 2016"  ""


.SH NAME
.PP
openshift cli adm config set\-cluster \- Sets a cluster entry in kubeconfig


.SH SYNOPSIS
.PP
\fBopenshift cli adm config set\-cluster\fP [OPTIONS]


.SH DESCRIPTION
.PP
Sets a cluster entry in kubeconfig. Specifying a name that already exists will merge new fields on top of existing values for those fields.


.SH OPTIONS
.PP
\fB\-\-api\-version\fP=""
    api\-version for the cluster entry in kubeconfig

.PP
\fB\-\-certificate\-authority\fP=""
    path to certificate\-authority file for the cluster entry in kubeconfig

.PP
\fB\-\-embed\-certs\fP=false
    embed\-certs for the cluster entry in kubeconfig

.PP
\fB\-\-insecure\-skip\-tls\-verify\fP=false
    insecure\-skip\-tls\-verify for the cluster entry in kubeconfig

.PP
\fB\-\-server\fP=""
    server for the cluster entry in kubeconfig


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-as\fP=""
    Username to impersonate for the operation

.PP
\fB\-\-client\-certificate\fP=""
    Path to a client certificate file for TLS

.PP
\fB\-\-client\-key\fP=""
    Path to a client key file for TLS

.PP
\fB\-\-cluster\fP=""
    The name of the kubeconfig cluster to use

.PP
\fB\-\-config\fP=""
    use a particular kubeconfig file

.PP
\fB\-\-context\fP=""
    The name of the kubeconfig context to use

.PP
\fB\-\-google\-json\-key\fP=""
    The Google Cloud Platform Service Account JSON Key to use for authentication.

.PP
\fB\-\-log\-flush\-frequency\fP=0
    Maximum number of seconds between log flushes

.PP
\fB\-\-match\-server\-version\fP=false
    Require server version to match client version

.PP
\fB\-n\fP, \fB\-\-namespace\fP=""
    If present, the namespace scope for this CLI request

.PP
\fB\-\-request\-timeout\fP="0"
    The length of time to wait before giving up on a single server request. Non\-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests.

.PP
\fB\-\-token\fP=""
    Bearer token for authentication to the API server

.PP
\fB\-\-user\fP=""
    The name of the kubeconfig user to use


.SH EXAMPLE
.PP
.RS

.nf
  # Set only the server field on the e2e cluster entry without touching other values.
  openshift cli adm config set\-cluster e2e \-\-server=https://1.2.3.4
  
  # Embed certificate authority data for the e2e cluster entry
  openshift cli adm config set\-cluster e2e \-\-certificate\-authority=\~/.kube/e2e/kubernetes.ca.crt
  
  # Disable cert checking for the dev cluster entry
  openshift cli adm config set\-cluster e2e \-\-insecure\-skip\-tls\-verify=true

.fi
.RE


.SH SEE ALSO
.PP
\fBopenshift\-cli\-adm\-config(1)\fP,


.SH HISTORY
.PP
June 2016, Ported from the Kubernetes man\-doc generator
