.TH "OPENSHIFT CLI ROLLOUT" "1" " Openshift CLI User Manuals" "Openshift" "June 2016"  ""


.SH NAME
.PP
openshift cli rollout undo \- Undo a previous rollout


.SH SYNOPSIS
.PP
\fBopenshift cli rollout undo\fP [OPTIONS]


.SH DESCRIPTION
.PP
Revert an application back to a previous deployment

.PP
When you run this command your deployment configuration will be updated to match a previous deployment. By default only the pod and container configuration will be changed and scaling or trigger settings will be left as\- is. Note that environment variables and volumes are included in rollbacks, so if you've recently updated security credentials in your environment your previous deployment may not have the correct values.

.PP
Any image triggers present in the rolled back configuration will be disabled with a warning. This is to help prevent your rolled back deployment from being replaced by a triggered deployment soon after your rollback. To re\-enable the triggers, use the 'deploy \-\-enable\-triggers' command.

.PP
If you would like to review the outcome of the rollback, pass '\-\-dry\-run' to print a human\-readable representation of the updated deployment configuration instead of executing the rollback. This is useful if you're not quite sure what the outcome will be.


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-filename\fP=[]
    Filename, directory, or URL to a file identifying the resource to get from a server.

.PP
\fB\-R\fP, \fB\-\-recursive\fP=false
    Process the directory used in \-f, \-\-filename recursively. Useful when you want to manage related manifests organized within the same directory.

.PP
\fB\-\-to\-revision\fP=0
    The revision to rollback to. Default to 0 (last revision).


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-api\-version\fP=""
    DEPRECATED: The API version to use when talking to the server

.PP
\fB\-\-as\fP=""
    Username to impersonate for the operation

.PP
\fB\-\-certificate\-authority\fP=""
    Path to a cert. file for the certificate authority

.PP
\fB\-\-client\-certificate\fP=""
    Path to a client certificate file for TLS

.PP
\fB\-\-client\-key\fP=""
    Path to a client key file for TLS

.PP
\fB\-\-cluster\fP=""
    The name of the kubeconfig cluster to use

.PP
\fB\-\-config\fP=""
    Path to the config file to use for CLI requests.

.PP
\fB\-\-context\fP=""
    The name of the kubeconfig context to use

.PP
\fB\-\-google\-json\-key\fP=""
    The Google Cloud Platform Service Account JSON Key to use for authentication.

.PP
\fB\-\-insecure\-skip\-tls\-verify\fP=false
    If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure

.PP
\fB\-\-log\-flush\-frequency\fP=0
    Maximum number of seconds between log flushes

.PP
\fB\-\-match\-server\-version\fP=false
    Require server version to match client version

.PP
\fB\-n\fP, \fB\-\-namespace\fP=""
    If present, the namespace scope for this CLI request

.PP
\fB\-\-request\-timeout\fP="0"
    The length of time to wait before giving up on a single server request. Non\-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests.

.PP
\fB\-\-server\fP=""
    The address and port of the Kubernetes API server

.PP
\fB\-\-token\fP=""
    Bearer token for authentication to the API server

.PP
\fB\-\-user\fP=""
    The name of the kubeconfig user to use


.SH EXAMPLE
.PP
.RS

.nf
  # Rollback to the previous deployment
  openshift cli rollout undo dc/nginx
  
  # Rollback to deployment revision 3. The replication controller for that version must exist.
  openshift cli rollout undo dc/nginx \-\-to\-revision=3

.fi
.RE


.SH SEE ALSO
.PP
\fBopenshift\-cli\-rollout(1)\fP,


.SH HISTORY
.PP
June 2016, Ported from the Kubernetes man\-doc generator
