.TH "OPENSHIFT" "1" " Openshift CLI User Manuals" "Openshift" "June 2016"  ""


.SH NAME
.PP
openshift completion \- Output shell completion code for the given shell (bash or zsh)


.SH SYNOPSIS
.PP
\fBopenshift completion\fP [OPTIONS]


.SH DESCRIPTION
.PP
This command prints shell code which must be evaluated to provide interactive completion of openshift commands.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-google\-json\-key\fP=""
    The Google Cloud Platform Service Account JSON Key to use for authentication.

.PP
\fB\-\-log\-flush\-frequency\fP=0
    Maximum number of seconds between log flushes


.SH EXAMPLE
.PP
.RS

.nf
  # Generate the openshift completion code for bash
  openshift completion bash > bash\_completion.sh
  source bash\_completion.sh
  
  # The above example depends on the bash\-completion framework.
  # It must be sourced before sourcing the openshift cli completion,
  # i.e. on the Mac:
  
  brew install bash\-completion
  source $(brew \-\-prefix)/etc/bash\_completion
  openshift completion bash > bash\_completion.sh
  source bash\_completion.sh
  
  # In zsh*, the following will load openshift cli zsh completion:
  source <(openshift completion zsh)
  
  * zsh completions are only supported in versions of zsh >= 5.2

.fi
.RE


.SH SEE ALSO
.PP
\fBopenshift(1)\fP,


.SH HISTORY
.PP
June 2016, Ported from the Kubernetes man\-doc generator
