.TH "OPENSHIFT" "1" " Openshift CLI User Manuals" "Openshift" "June 2016"  ""


.SH NAME
.PP
openshift infra \-


.SH SYNOPSIS
.PP
\fBopenshift infra\fP [OPTIONS]


.SH DESCRIPTION

.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-google\-json\-key\fP=""
    The Google Cloud Platform Service Account JSON Key to use for authentication.

.PP
\fB\-\-log\-flush\-frequency\fP=0
    Maximum number of seconds between log flushes


.SH SEE ALSO
.PP
\fBopenshift(1)\fP, \fBopenshift\-infra\-deploy(1)\fP, \fBopenshift\-infra\-diagnostic\-pod(1)\fP, \fBopenshift\-infra\-docker\-build(1)\fP, \fBopenshift\-infra\-f5\-router(1)\fP, \fBopenshift\-infra\-network\-diagnostic\-pod(1)\fP, \fBopenshift\-infra\-recycle(1)\fP, \fBopenshift\-infra\-router(1)\fP, \fBopenshift\-infra\-sti\-build(1)\fP,


.SH HISTORY
.PP
June 2016, Ported from the Kubernetes man\-doc generator
