.TH "OPENSHIFT START" "1" " Openshift CLI User Manuals" "Openshift" "June 2016"  ""


.SH NAME
.PP
openshift start kubernetes \- Kubernetes server components


.SH SYNOPSIS
.PP
\fBopenshift start kubernetes\fP [OPTIONS]


.SH DESCRIPTION
.PP
Start Kubernetes server components

.PP
The primary Kubernetes server components can be started individually using their direct
arguments. No configuration settings will be used when launching these components.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-google\-json\-key\fP=""
    The Google Cloud Platform Service Account JSON Key to use for authentication.

.PP
\fB\-\-log\-flush\-frequency\fP=0
    Maximum number of seconds between log flushes


.SH SEE ALSO
.PP
\fBopenshift\-start(1)\fP, \fBopenshift\-start\-kubernetes\-apiserver(1)\fP, \fBopenshift\-start\-kubernetes\-controller\-manager(1)\fP, \fBopenshift\-start\-kubernetes\-kubelet(1)\fP, \fBopenshift\-start\-kubernetes\-proxy(1)\fP, \fBopenshift\-start\-kubernetes\-scheduler(1)\fP,


.SH HISTORY
.PP
June 2016, Ported from the Kubernetes man\-doc generator
