.TH "OPENSHIFT INFRA" "1" " Openshift CLI User Manuals" "Openshift" "June 2016"  ""


.SH NAME
.PP
openshift infra deploy \- Run the deployer


.SH SYNOPSIS
.PP
\fBopenshift infra deploy\fP [OPTIONS]


.SH DESCRIPTION
.PP
Perform a deployment

.PP
This command launches a deployment as described by a deployment configuration. It accepts the name of a replication controller created by a deployment and runs that deployment to completion. You can use the \-\-until flag to run the deployment until you reach the specified condition.

.PP
Available conditions:
.IP 

.IP
\(bu "start": after old deployments are scaled to zero
.br
.IP
\(bu "pre": after the pre hook completes (even if no hook specified)
.br
.IP
\(bu "mid": after the mid hook completes (even if no hook specified)
.br
.IP
\(bu A percentage of the deployment, based on which strategy is in use
.br
.IP 

.IP
\(bu "0%"   Recreate after the previous deployment is scaled to zero
.br
.IP
\(bu "N%"   Recreate after the acceptance check if this is not the first deployment
.br
.IP
\(bu "0%"   Rolling  before the rolling deployment is started, equivalent to "pre"
.br
.IP
\(bu "N%"   Rolling  the percentage of pods in the target deployment that are ready
.br
.IP
\(bu "100%" All      after the deployment is at full scale, but before the post hook runs
.br
.PP
Unrecognized conditions will be ignored and the deployment will run to completion. You can run this command multiple times when \-\-until is specified \- hooks will only be executed once.


.SH OPTIONS
.PP
\fB\-\-deployment\fP=""
    The deployment name to start

.PP
\fB\-\-namespace\fP=""
    The deployment namespace

.PP
\fB\-\-until\fP=""
    Exit the deployment when this condition is met. See help for more details


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-google\-json\-key\fP=""
    The Google Cloud Platform Service Account JSON Key to use for authentication.

.PP
\fB\-\-log\-flush\-frequency\fP=0
    Maximum number of seconds between log flushes


.SH SEE ALSO
.PP
\fBopenshift\-infra(1)\fP, \fBopenshift\-infra\-deploy\-version(1)\fP,


.SH HISTORY
.PP
June 2016, Ported from the Kubernetes man\-doc generator
