.TH "OPENSHIFT" "1" " Openshift CLI User Manuals" "Openshift" "June 2016"  ""


.SH NAME
.PP
openshift version \- Display client and server versions


.SH SYNOPSIS
.PP
\fBopenshift version\fP [OPTIONS]


.SH DESCRIPTION
.PP
Display client and server versions.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-google\-json\-key\fP=""
    The Google Cloud Platform Service Account JSON Key to use for authentication.

.PP
\fB\-\-log\-flush\-frequency\fP=0
    Maximum number of seconds between log flushes


.SH SEE ALSO
.PP
\fBopenshift(1)\fP,


.SH HISTORY
.PP
June 2016, Ported from the Kubernetes man\-doc generator
