.TH "OPENSHIFT START" "1" " Openshift CLI User Manuals" "Openshift" "June 2016"  ""


.SH NAME
.PP
openshift start network \- Launch node network


.SH SYNOPSIS
.PP
\fBopenshift start network\fP [OPTIONS]


.SH DESCRIPTION
.PP
Start node network components

.PP
This command helps you launch node networking.  Running

.PP
openshift start network \-\-config=<node-config>

.PP
will start the network proxy and SDN plugins with given configuration file. The proxy will run in the foreground until you terminate the process.


.SH OPTIONS
.PP
\fB\-\-config\fP=""
    Location of the node configuration file to run from. When running from a configuration file, all other command\-line arguments are ignored.

.PP
\fB\-\-disable\fP=""
    The set of network components to disable

.PP
\fB\-\-enable\fP="plugins,proxy"
    The set of network components to enable

.PP
\fB\-\-images\fP="openshift/origin\-${component}:${version}"
    When fetching images used by the cluster for important components, use this format on both master and nodes. The latest release will be used by default.

.PP
\fB\-\-kubeconfig\fP=""
    Path to the kubeconfig file to use for requests to the Kubernetes API.

.PP
\fB\-\-kubernetes\fP="
\[la]https://localhost:8443"\[ra]
    removed in favor of \-\-kubeconfig

.PP
\fB\-\-latest\-images\fP=false
    If true, attempt to use the latest images for the cluster instead of the latest release.

.PP
\fB\-\-network\-plugin\fP=""
    The network plugin to be called for configuring networking for pods.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-google\-json\-key\fP=""
    The Google Cloud Platform Service Account JSON Key to use for authentication.

.PP
\fB\-\-log\-flush\-frequency\fP=0
    Maximum number of seconds between log flushes


.SH SEE ALSO
.PP
\fBopenshift\-start(1)\fP,


.SH HISTORY
.PP
June 2016, Ported from the Kubernetes man\-doc generator
