.TH "OPENSHIFT" "1" " Openshift CLI User Manuals" "Openshift" "June 2016"  ""


.SH NAME
.PP
openshift \- Build, deploy, and manage your cloud applications


.SH SYNOPSIS
.PP
\fBopenshift\fP [OPTIONS]


.SH DESCRIPTION
.PP
OpenShift Application Platform

.PP
The OpenShift distribution of Kubernetes helps you build, deploy, and manage your applications on top of Docker containers. To start an all\-in\-one server with the default configuration, run:

.PP
$ openshift start \&


.SH OPTIONS
.PP
\fB\-\-google\-json\-key\fP=""
    The Google Cloud Platform Service Account JSON Key to use for authentication.

.PP
\fB\-\-log\-flush\-frequency\fP=0
    Maximum number of seconds between log flushes


.SH SEE ALSO
.PP
\fBopenshift\-admin(1)\fP, \fBopenshift\-cli(1)\fP, \fBopenshift\-completion(1)\fP, \fBopenshift\-ex(1)\fP, \fBopenshift\-infra(1)\fP, \fBopenshift\-kube(1)\fP, \fBopenshift\-options(1)\fP, \fBopenshift\-start(1)\fP, \fBopenshift\-version(1)\fP,


.SH HISTORY
.PP
June 2016, Ported from the Kubernetes man\-doc generator
