.TH "OPENSHIFT START KUBERNETES" "1" " Openshift CLI User Manuals" "Openshift" "June 2016"  ""


.SH NAME
.PP
openshift start kubernetes scheduler \- Launch Kubernetes scheduler (kube\-scheduler)


.SH SYNOPSIS
.PP
\fBopenshift start kubernetes scheduler\fP [OPTIONS]


.SH DESCRIPTION
.PP
Start Kubernetes controller manager

.PP
This command launches an instance of the Kubernetes controller\-manager (kube\-controller\-manager).


.SH OPTIONS
.PP
\fB\-\-address\fP="0.0.0.0"
    The IP address to serve on (set to 0.0.0.0 for all interfaces)

.PP
\fB\-\-algorithm\-provider\fP="DefaultProvider"
    The scheduling algorithm provider to use, one of: ClusterAutoscalerProvider | DefaultProvider

.PP
\fB\-\-bind\-pods\-burst\fP=0
    unused, use \-\-kube\-api\-burst

.PP
\fB\-\-bind\-pods\-qps\fP=0
    unused, use \-\-kube\-api\-qps

.PP
\fB\-\-failure\-domains\fP="kubernetes.io/hostname,failure\-domain.beta.kubernetes.io/zone,failure\-domain.beta.kubernetes.io/region"
    Indicate the "all topologies" set for an empty topologyKey when it's used for PreferredDuringScheduling pod anti\-affinity.

.PP
\fB\-\-feature\-gates\fP=
    A set of key=value pairs that describe feature gates for alpha/experimental features. Options are:
AllAlpha=true|false (ALPHA \- default=false)
AllowExtTrafficLocalEndpoints=true|false (ALPHA \- default=false)
AppArmor=true|false (BETA \- default=true)
DynamicKubeletConfig=true|false (ALPHA \- default=false)
DynamicVolumeProvisioning=true|false (ALPHA \- default=true)

.PP
\fB\-\-hard\-pod\-affinity\-symmetric\-weight\fP=1
    RequiredDuringScheduling affinity is not symmetric, but there is an implicit PreferredDuringScheduling affinity rule corresponding to every RequiredDuringScheduling affinity rule. \-\-hard\-pod\-affinity\-symmetric\-weight represents the weight of implicit PreferredDuringScheduling affinity rule.

.PP
\fB\-\-kube\-api\-burst\fP=100
    Burst to use while talking with kubernetes apiserver

.PP
\fB\-\-kube\-api\-content\-type\fP="application/vnd.kubernetes.protobuf"
    Content type of requests sent to apiserver.

.PP
\fB\-\-kube\-api\-qps\fP=50
    QPS to use while talking with kubernetes apiserver

.PP
\fB\-\-kubeconfig\fP=""
    Path to kubeconfig file with authorization and master location information.

.PP
\fB\-\-leader\-elect\fP=true
    Start a leader election client and gain leadership before executing the main loop. Enable this when running replicated components for high availability.

.PP
\fB\-\-leader\-elect\-lease\-duration\fP=0
    The duration that non\-leader candidates will wait after observing a leadership renewal until attempting to acquire leadership of a led but unrenewed leader slot. This is effectively the maximum duration that a leader can be stopped before it is replaced by another candidate. This is only applicable if leader election is enabled.

.PP
\fB\-\-leader\-elect\-renew\-deadline\fP=0
    The interval between attempts by the acting master to renew a leadership slot before it stops leading. This must be less than or equal to the lease duration. This is only applicable if leader election is enabled.

.PP
\fB\-\-leader\-elect\-retry\-period\fP=0
    The duration the clients should wait between attempting acquisition and renewal of a leadership. This is only applicable if leader election is enabled.

.PP
\fB\-\-master\fP=""
    The address of the Kubernetes API server (overrides any value in kubeconfig)

.PP
\fB\-\-policy\-config\-file\fP=""
    File with scheduler policy configuration

.PP
\fB\-\-port\fP=10251
    The port that the scheduler's http service runs on

.PP
\fB\-\-profiling\fP=true
    Enable profiling via web interface host:port/debug/pprof/

.PP
\fB\-\-scheduler\-name\fP="default\-scheduler"
    Name of the scheduler, used to select which pods will be processed by this scheduler, based on pod's annotation with key 'scheduler.alpha.kubernetes.io/name'


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-google\-json\-key\fP=""
    The Google Cloud Platform Service Account JSON Key to use for authentication.

.PP
\fB\-\-log\-flush\-frequency\fP=0
    Maximum number of seconds between log flushes


.SH SEE ALSO
.PP
\fBopenshift\-start\-kubernetes(1)\fP,


.SH HISTORY
.PP
June 2016, Ported from the Kubernetes man\-doc generator
