.TH "OPENSHIFT CLI CONFIG" "1" " Openshift CLI User Manuals" "Openshift" "June 2016"  ""


.SH NAME
.PP
openshift cli config set\-credentials \- Sets a user entry in kubeconfig


.SH SYNOPSIS
.PP
\fBopenshift cli config set\-credentials\fP [OPTIONS]


.SH DESCRIPTION
.PP
Sets a user entry in kubeconfig Specifying a name that already exists will merge new fields on top of existing values.

.PP
Client\-certificate flags: \-\-client\-certificate=certfile \-\-client\-key=keyfile

.PP
Bearer token flags: \-\-token=bearer \_token

.PP
Basic auth flags: \-\-username=basic user \-\-password=basic password

.PP
Bearer token and basic auth are mutually exclusive.


.SH OPTIONS
.PP
\fB\-\-auth\-provider\fP=""
    auth provider for the user entry in kubeconfig

.PP
\fB\-\-auth\-provider\-arg\fP=[]
    'key=value' arugments for the auth provider

.PP
\fB\-\-client\-certificate\fP=""
    path to client\-certificate file for the user entry in kubeconfig

.PP
\fB\-\-client\-key\fP=""
    path to client\-key file for the user entry in kubeconfig

.PP
\fB\-\-embed\-certs\fP=false
    embed client cert/key for the user entry in kubeconfig

.PP
\fB\-\-password\fP=""
    password for the user entry in kubeconfig

.PP
\fB\-\-token\fP=""
    token for the user entry in kubeconfig

.PP
\fB\-\-username\fP=""
    username for the user entry in kubeconfig


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-api\-version\fP=""
    DEPRECATED: The API version to use when talking to the server

.PP
\fB\-\-as\fP=""
    Username to impersonate for the operation

.PP
\fB\-\-certificate\-authority\fP=""
    Path to a cert. file for the certificate authority

.PP
\fB\-\-cluster\fP=""
    The name of the kubeconfig cluster to use

.PP
\fB\-\-config\fP=""
    use a particular kubeconfig file

.PP
\fB\-\-context\fP=""
    The name of the kubeconfig context to use

.PP
\fB\-\-google\-json\-key\fP=""
    The Google Cloud Platform Service Account JSON Key to use for authentication.

.PP
\fB\-\-insecure\-skip\-tls\-verify\fP=false
    If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure

.PP
\fB\-\-log\-flush\-frequency\fP=0
    Maximum number of seconds between log flushes

.PP
\fB\-\-match\-server\-version\fP=false
    Require server version to match client version

.PP
\fB\-n\fP, \fB\-\-namespace\fP=""
    If present, the namespace scope for this CLI request

.PP
\fB\-\-request\-timeout\fP="0"
    The length of time to wait before giving up on a single server request. Non\-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests.

.PP
\fB\-\-server\fP=""
    The address and port of the Kubernetes API server

.PP
\fB\-\-user\fP=""
    The name of the kubeconfig user to use


.SH EXAMPLE
.PP
.RS

.nf
  # Set only the "client\-key" field on the "cluster\-admin"
  # entry, without touching other values:
  openshift cli config set\-credentials cluster\-admin \-\-client\-key=\~/.kube/admin.key
  
  # Set basic auth for the "cluster\-admin" entry
  openshift cli config set\-credentials cluster\-admin \-\-username=admin \-\-password=uXFGweU9l35qcif
  
  # Embed client certificate data in the "cluster\-admin" entry
  openshift cli config set\-credentials cluster\-admin \-\-client\-certificate=\~/.kube/admin.crt \-\-embed\-certs=true
  
  # Enable the Google Compute Platform auth provider for the "cluster\-admin" entry
  openshift cli config set\-credentials cluster\-admin \-\-auth\-provider=gcp
  
  # Enable the OpenID Connect auth provider for the "cluster\-admin" entry with additional args
  openshift cli config set\-credentials cluster\-admin \-\-auth\-provider=oidc \-\-auth\-provider\-arg=client\-id=foo \-\-auth\-provider\-arg=client\-secret=bar
  
  # Remove the "client\-secret" config value for the OpenID Connect auth provider for the "cluster\-admin" entry
  openshift cli config set\-credentials cluster\-admin \-\-auth\-provider=oidc \-\-auth\-provider\-arg=client\-secret\-

.fi
.RE


.SH SEE ALSO
.PP
\fBopenshift\-cli\-config(1)\fP,


.SH HISTORY
.PP
June 2016, Ported from the Kubernetes man\-doc generator
