= v1.APIGroupList
{product-author}
{product-version}
:data-uri:
:icons:
:toc: macro
:toc-title:
:toclevels: 2

toc::[]

== Description
[%hardbreaks]
APIGroupList is a list of APIGroup, to allow clients to discover the API at /apis.

== Object Schema
Expand or mouse-over a field for more information about it.

++++
<pre>
<div style="margin-left:13px;"><span title="(string) APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources">apiVersion</span>:
</div><details><summary><span title="(array) groups is a list of APIGroup.">groups</span>:
</summary><div style="margin-left:13px;">- <span title="(string) APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources">apiVersion</span>:
</div><div style="margin-left:13px;">  <span title="(string) Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds">kind</span>:
</div><div style="margin-left:13px;">  <span title="(string) name is the name of the group.">name</span>:
</div><details><summary>  <span title="(v1.GroupVersionForDiscovery) preferredVersion is the version preferred by the API server, which probably is the storage version.">preferredVersion</span>:
</summary><div style="margin-left:13px;">    <span title="(string) groupVersion specifies the API group and version in the form &#34;group/version&#34;">groupVersion</span>:
</div><div style="margin-left:13px;">    <span title="(string) version specifies the version in the form of &#34;version&#34;. This is to save the clients the trouble of splitting the GroupVersion.">version</span>:
</div></details><details><summary>  <span title="(array) a map of client CIDR to server address that is serving this group. This is to help clients reach servers in the most network-efficient way possible. Clients can use the appropriate server address as per the CIDR that they match. In case of multiple matches, clients should use the longest matching CIDR. The server returns only those CIDRs that it thinks that the client can match. For example: the master will return an internal IP CIDR only, if the client reaches the server using an internal IP. Server looks at X-Forwarded-For header or X-Real-Ip header or request.RemoteAddr (in that order) to get the client IP.">serverAddressByClientCIDRs</span>:
</summary><div style="margin-left:13px;">  - <span title="(string) The CIDR with which clients can match their IP to figure out the server address that they should use.">clientCIDR</span>:
</div><div style="margin-left:13px;">    <span title="(string) Address of this server, suitable for a client that matches the above CIDR. This can be a hostname, hostname:port, IP or IP:port.">serverAddress</span>:
</div></details><details><summary>  <span title="(array) versions are the versions supported in this group.">versions</span>:
</summary><div style="margin-left:13px;">  - <span title="(string) groupVersion specifies the API group and version in the form &#34;group/version&#34;">groupVersion</span>:
</div><div style="margin-left:13px;">    <span title="(string) version specifies the version in the form of &#34;version&#34;. This is to save the clients the trouble of splitting the GroupVersion.">version</span>:
</div></details></details><div style="margin-left:13px;"><span title="(string) Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds">kind</span>:
</div>
</pre>
++++

== Operations

[[Get-apis]]
=== Get all APIGroupLists
Get available API versions

==== HTTP request
----
GET /apis/ HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
----

==== Curl request
----
$ curl -k \
    -H "Authorization: Bearer $TOKEN" \
    -H 'Accept: application/json' \
    https://$ENDPOINT/apis/
----

==== Responses
[cols="1,5", options="header"]
|===
|HTTP Code|Schema
|200 OK|v1.APIGroupList
|401 Unauthorized|
|===

==== Consumes

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf

==== Produces

* application/json
* application/yaml
* application/vnd.kubernetes.protobuf



