{{- $ca := genCA "svc-cat-ca" 3650 }}
{{- $cn := printf "%s-catalog-apiserver" .Release.Name }}
{{- $altName1 := printf "%s-catalog-apiserver.%s" .Release.Name .Release.Namespace }}
{{- $altName2 := printf "%s-catalog-apiserver.%s.svc" .Release.Name .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $altName1 $altName2) 3650 $ca }}
{{- if .Values.useAggregator }}
{{- if .Capabilities.APIVersions.Has "apiregistration.k8s.io/v1beta1" }}
apiVersion: apiregistration.k8s.io/v1beta1
{{- else if .Capabilities.APIVersions.Has "apiregistration.k8s.io/v1alpha1" }}
apiVersion: apiregistration.k8s.io/v1alpha1
{{- end }}
kind: APIService
metadata:
  name: v1beta1.servicecatalog.k8s.io
spec:
  group: servicecatalog.k8s.io
  version: v1beta1
  service:
    namespace: {{ .Release.Namespace }}
    name: {{ template "fullname" . }}-apiserver
  caBundle: {{ b64enc $ca.Cert }}
  {{ if .Capabilities.APIVersions.Has "apiregistration.k8s.io/v1alpha1" -}}
  priority: {{ .Values.apiserver.aggregator.priority }}
  {{ else if .Capabilities.APIVersions.Has "apiregistration.k8s.io/v1beta1" -}}
  groupPriorityMinimum: {{ .Values.apiserver.aggregator.groupPriorityMinimum }}
  versionPriority: {{ .Values.apiserver.aggregator.versionPriority }}
  {{- end }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-apiserver-cert
  labels:
    app: {{ template "fullname" . }}-apiserver
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
  {{- if .Values.apiserver.tls.requestHeaderCA }}
  requestheader-ca.crt: {{ .Values.apiserver.tls.requestHeaderCA }}
  {{- end }}
