// This package is generated by client-gen with arguments: --clientset-name=internalclientset --clientset-path=github.com/openshift/origin/pkg/quota/clientset --go-header-file=hack/boilerplate.txt --group=quota --input=[api/] --input-base=github.com/openshift/origin/pkg/quota --output-base=../../..

// This package has the automatically generated fake clientset.
package fake
