.\" Manpage for atomic-registry-install.
.TH man 8 "17 Aug 2016" "0.1" "atomic-registry-install man page"
.SH NAME
atomic-registry-install \- Atomic Registry installer image
.SH SYNOPSIS
atomic install projectatomic/atomic-registry-install [HOSTNAME]
.PP
atomic uninstall projectatomic/atomic-registry-install [--remove-data]
.SH DESCRIPTION
A container-based installation of Atomic Registry. It installs systemd unit files, configuration and a setup script to deploy atomic registry. It supports overriding image names, tags and ports used for Atomic Registry.
.SH OPTIONS
.IP HOSTNAME
installation hostname. By default the output of `hostname` is used.
.B install
only.

.IP --remove-data
destructively remove all configuration and datastore.
.B uninstall
only.
.SH ENVIRONMENT
Installation values may be overridden by environment variable. The following variables are passed into the installation container:
.IP REGISTRYPORT=5000
The registry service port
.IP MASTERPORT=8443
The master service port
.IP CONSOLEPORT=9090
The console service port
.IP REGISTRYIMAGE=openshift/origin-docker-registry
The registry container image
.IP MASTERIMAGE=openshift/origin
The master container image
.IP CONSOLEIMAGE=cockpit/kubernetes
The console container image
.IP REGISTRYTAG=latest
The registry container tag
.IP MASTERTAG=latest
The master container tag
.IP CONSOLETAG=latest
The console container tag

.SH EXAMPLES
.B Install
using custom hostname and default images, tags and ports
.RS
sudo atomic install projectatomic/atomic-registry-install registry.example.com
.RE

.B Install,
overriding default ports and tags
.RS
sudo REGISTRYPORT=443 CONSOLEPORT=8080 MASTERTAG=v1.3.0-alpha.1 REGISTRYTAG=v1.3.0-alpha.1 atomic install projectatomic/atomic-registry-install
.RE

.B Uninstall,
removing configuration and datastore. This is a
.B "destructive uninstall. All data will be lost."
.RS
sudo atomic uninstall projectatomic/atomic-registry-install --remove-data
.RE

.SH SEE ALSO
atomic-install(1), atomic-uninstall(1), docker(1)
.SH AUTHOR
Aaron Weitekamp (aweiteka@redhat.com)
