// This file was automatically generated by lister-gen

package v1

// OAuthClientListerExpansion allows custom methods to be added to
// OAuthClientLister.
type OAuthClientListerExpansion interface{}

// OAuthClientNamespaceListerExpansion allows custom methods to be added to
// OAuthClientNamespaeLister.
type OAuthClientNamespaceListerExpansion interface{}
